/**
 * Copyright (c) 2020 The JavaSSH Project
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 */
package ssh;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
import ssh.SshLibrary.sftp_ext;
import ssh.SshLibrary.ssh_channel;
import ssh.SshLibrary.ssh_session;
/**
 * <i>native declaration : /usr/include/libssh/sftp.h:25</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sftp_session_struct extends Structure {
	/** C type : ssh_session */
	public ssh_session session;
	/** C type : ssh_channel */
	public ssh_channel channel;
	public int server_version;
	public int client_version;
	public int version;
	/** C type : sftp_request_queue */
	public ssh.sftp_request_queue_struct.ByReference queue;
	public int id_counter;
	public int errnum;
	/** C type : void** */
	public PointerByReference handles;
	/** C type : sftp_ext */
	public sftp_ext ext;
	public sftp_session_struct() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("session", "channel", "server_version", "client_version", "version", "queue", "id_counter", "errnum", "handles", "ext");
	}
	public sftp_session_struct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends sftp_session_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends sftp_session_struct implements Structure.ByValue {
		
	};
}
