package ssh;
import java.util.Arrays;
import java.util.List;

import com.ochafik.lang.jnaerator.runtime.Structure;
import ssh.SshLibrary.ssh_buffer;
/**
 * <i>native declaration : /usr/include/libssh/sftp.h:88</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sftp_packet_struct extends Structure<sftp_packet_struct, sftp_packet_struct.ByValue, sftp_packet_struct.ByReference > {
	/// C type : sftp_session
	public ssh.sftp_session_struct.ByReference sftp;
	public byte type;
	/// C type : ssh_buffer
	public ssh_buffer payload;
	public sftp_packet_struct() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList(new java.lang.String[]{"sftp", "type", "payload"});
	}
	/**
	 * @param sftp C type : sftp_session<br>
	 * @param payload C type : ssh_buffer
	 */
	public sftp_packet_struct(ssh.sftp_session_struct.ByReference sftp, byte type, ssh_buffer payload) {
		super();
		this.sftp = sftp;
		this.type = type;
		this.payload = payload;
	}
	@Override
	protected ByReference newByReference() { return new ByReference(); }
	@Override
	protected ByValue newByValue() { return new ByValue(); }
	@Override
	protected sftp_packet_struct newInstance() { return new sftp_packet_struct(); }
	public static sftp_packet_struct[] newArray(int arrayLength) {
		return Structure.newArray(sftp_packet_struct.class, arrayLength);
	}
	public static class ByReference extends sftp_packet_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends sftp_packet_struct implements Structure.ByValue {
		
	};
}
