package ssh;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import ssh.SshLibrary.ssh_string;
/**
 * SSH_FXP_MESSAGE described into .7 page 26<br>
 * <i>native declaration : /usr/include/libssh/sftp.h:83</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sftp_status_message_struct extends Structure {
	public int id;
	public int status;
	/**
	 * not used anymore<br>
	 * C type : ssh_string
	 */
	public ssh_string error_unused;
	/**
	 * not used anymore<br>
	 * C type : ssh_string
	 */
	public ssh_string lang_unused;
	/** C type : char* */
	public Pointer errormsg;
	/** C type : char* */
	public Pointer langmsg;
	public sftp_status_message_struct() {
		super();
	}
	@Override
	protected List<String > getFieldOrder() {
		return Arrays.asList("id", "status", "error_unused", "lang_unused", "errormsg", "langmsg");
	}
	/**
	 * @param error_unused not used anymore<br>
	 * C type : ssh_string<br>
	 * @param lang_unused not used anymore<br>
	 * C type : ssh_string<br>
	 * @param errormsg C type : char*<br>
	 * @param langmsg C type : char*
	 */
	public sftp_status_message_struct(int id, int status, ssh_string error_unused, ssh_string lang_unused, Pointer errormsg, Pointer langmsg) {
		super();
		this.id = id;
		this.status = status;
		this.error_unused = error_unused;
		this.lang_unused = lang_unused;
		this.errormsg = errormsg;
		this.langmsg = langmsg;
	}
	public sftp_status_message_struct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends sftp_status_message_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends sftp_status_message_struct implements Structure.ByValue {
		
	};
}
