package ssh;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import ssh.SshLibrary.ssh_string;
/**
 * <i>native declaration : /usr/include/libssh/sftp.h:107</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sftp_attributes_struct extends Structure {
	/** C type : char* */
	public Pointer name;
	/**
	 * ls -l output on openssh, not reliable else<br>
	 * C type : char*
	 */
	public Pointer longname;
	public int flags;
	public byte type;
	public long size;
	public int uid;
	public int gid;
	/**
	 * set if openssh and version 4<br>
	 * C type : char*
	 */
	public Pointer owner;
	/**
	 * set if openssh and version 4<br>
	 * C type : char*
	 */
	public Pointer group;
	public int permissions;
	public long atime64;
	public int atime;
	public int atime_nseconds;
	public long createtime;
	public int createtime_nseconds;
	public long mtime64;
	public int mtime;
	public int mtime_nseconds;
	/** C type : ssh_string */
	public ssh_string acl;
	public int extended_count;
	/** C type : ssh_string */
	public ssh_string extended_type;
	/** C type : ssh_string */
	public ssh_string extended_data;
	public sftp_attributes_struct() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("name", "longname", "flags", "type", "size", "uid", "gid", "owner", "group", "permissions", "atime64", "atime", "atime_nseconds", "createtime", "createtime_nseconds", "mtime64", "mtime", "mtime_nseconds", "acl", "extended_count", "extended_type", "extended_data");
	}
	public sftp_attributes_struct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends sftp_attributes_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends sftp_attributes_struct implements Structure.ByValue {
		
	};
}
