/**
 * Copyright (c) 2020 The JavaSSH Project
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 */
package ssh;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * @brief SFTP statvfs structure.<br>
 *        <i>native declaration : /usr/include/libssh/sftp.h:121</i><br>
 *        This file was autogenerated by
 *        <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 *        a tool written by <a href="http://ochafik.com/">Olivier Chafik</a>
 *        that <a href=
 *        "http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 *        opensource projects.</a>.<br>
 *        For help, please visit
 *        <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> ,
 *        <a href="http://rococoa.dev.java.net/">Rococoa</a>, or
 *        <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sftp_statvfs_struct extends Structure {
	/** file system block size */
	public long f_bsize;
	/** fundamental fs block size */
	public long f_frsize;
	/** number of blocks (unit f_frsize) */
	public long f_blocks;
	/** free blocks in file system */
	public long f_bfree;
	/** free blocks for non-root */
	public long f_bavail;
	/** total file inodes */
	public long f_files;
	/** free file inodes */
	public long f_ffree;
	/** free file inodes for to non-root */
	public long f_favail;
	/** file system id */
	public long f_fsid;
	/** bit mask of f_flag values */
	public long f_flag;
	/** maximum filename length */
	public long f_namemax;

	public sftp_statvfs_struct() {
		super();
	}

	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("f_bsize", "f_frsize", "f_blocks", "f_bfree", "f_bavail", "f_files", "f_ffree", "f_favail", "f_fsid",
				"f_flag", "f_namemax");
	}

	public sftp_statvfs_struct(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends sftp_statvfs_struct implements Structure.ByReference {
	};

	public static class ByValue extends sftp_statvfs_struct implements Structure.ByValue {
	};
}
