package ssh;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import ssh.SshLibrary.ssh_string;
/**
 * file handler<br>
 * <i>native declaration : /usr/include/libssh/sftp.h:95</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sftp_file_struct extends Structure<sftp_file_struct, sftp_file_struct.ByValue, sftp_file_struct.ByReference > {
	/// C type : sftp_session
	public ssh.sftp_session_struct.ByReference sftp;
	/// C type : char*
	public Pointer name;
	public long offset;
	/// C type : ssh_string
	public ssh_string handle;
	public int eof;
	public int nonblocking;
	public sftp_file_struct() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"sftp", "name", "offset", "handle", "eof", "nonblocking"});
	}
	/**
	 * @param sftp C type : sftp_session<br>
	 * @param name C type : char*<br>
	 * @param handle C type : ssh_string
	 */
	public sftp_file_struct(ssh.sftp_session_struct.ByReference sftp, Pointer name, long offset, ssh_string handle, int eof, int nonblocking) {
		super();
		this.sftp = sftp;
		this.name = name;
		this.offset = offset;
		this.handle = handle;
		this.eof = eof;
		this.nonblocking = nonblocking;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected sftp_file_struct newInstance() { return new sftp_file_struct(); }
	public static sftp_file_struct[] newArray(int arrayLength) {
		return Structure.newArray(sftp_file_struct.class, arrayLength);
	}
	public static class ByReference extends sftp_file_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends sftp_file_struct implements Structure.ByValue {
		
	};
}
