package ssh;
import java.util.Arrays;
import java.util.List;

import com.ochafik.lang.jnaerator.runtime.Structure;
/**
 * <i>native declaration : /usr/include/libssh/sftp.h:176</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sftp_statvfs_struct extends Structure<sftp_statvfs_struct, sftp_statvfs_struct.ByValue, sftp_statvfs_struct.ByReference > {
	/// file system block size
	public long f_bsize;
	/// fundamental fs block size
	public long f_frsize;
	/// number of blocks (unit f_frsize)
	public long f_blocks;
	/// free blocks in file system
	public long f_bfree;
	/// free blocks for non-root
	public long f_bavail;
	/// total file inodes
	public long f_files;
	/// free file inodes
	public long f_ffree;
	/// free file inodes for to non-root
	public long f_favail;
	/// file system id
	public long f_fsid;
	/// bit mask of f_flag values
	public long f_flag;
	/// maximum filename length
	public long f_namemax;
	public sftp_statvfs_struct() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList(new java.lang.String[]{"f_bsize", "f_frsize", "f_blocks", "f_bfree", "f_bavail", "f_files", "f_ffree", "f_favail", "f_fsid", "f_flag", "f_namemax"});
	}
	@Override
	protected ByReference newByReference() { return new ByReference(); }
	@Override
	protected ByValue newByValue() { return new ByValue(); }
	@Override
	protected sftp_statvfs_struct newInstance() { return new sftp_statvfs_struct(); }
	public static sftp_statvfs_struct[] newArray(int arrayLength) {
		return Structure.newArray(sftp_statvfs_struct.class, arrayLength);
	}
	public static class ByReference extends sftp_statvfs_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends sftp_statvfs_struct implements Structure.ByValue {
		
	};
}
