package ssh;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
/**
 * <i>native declaration : /usr/include/libssh/callbacks.h:235</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ssh_packet_callbacks_struct extends Structure<ssh_packet_callbacks_struct, ssh_packet_callbacks_struct.ByValue, ssh_packet_callbacks_struct.ByReference > {
	/// Index of the first packet type being handled
	public byte start;
	/// Number of packets being handled by this callback struct
	public byte n_callbacks;
	/**
	 * A pointer to n_callbacks packet callbacks<br>
	 * @see ssh.SshLibrary.ssh_packet_callback<br>
	 * C type : ssh_packet_callback*
	 */
	public Pointer callbacks;
	/**
	 * User-provided data. User is free to set anything he wants here<br>
	 * C type : void*
	 */
	public Pointer user;
	public ssh_packet_callbacks_struct() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"start", "n_callbacks", "callbacks", "user"});
	}
	/**
	 * @param start Index of the first packet type being handled<br>
	 * @param n_callbacks Number of packets being handled by this callback struct<br>
	 * @param callbacks A pointer to n_callbacks packet callbacks<br>
	 * @see ssh.SshLibrary.ssh_packet_callback<br>
	 * C type : ssh_packet_callback*<br>
	 * @param user User-provided data. User is free to set anything he wants here<br>
	 * C type : void*
	 */
	public ssh_packet_callbacks_struct(byte start, byte n_callbacks, Pointer callbacks, Pointer user) {
		super();
		this.start = start;
		this.n_callbacks = n_callbacks;
		this.callbacks = callbacks;
		this.user = user;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected ssh_packet_callbacks_struct newInstance() { return new ssh_packet_callbacks_struct(); }
	public static ssh_packet_callbacks_struct[] newArray(int arrayLength) {
		return Structure.newArray(ssh_packet_callbacks_struct.class, arrayLength);
	}
	public static class ByReference extends ssh_packet_callbacks_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends ssh_packet_callbacks_struct implements Structure.ByValue {
		
	};
}
