/**
 * Copyright (c) 2020 The JavaSSH Project
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 */
package ssh;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import ssh.SshLibrary.SizeT;
import ssh.SshLibrary.ssh_auth_gssapi_mic_callback;
import ssh.SshLibrary.ssh_auth_none_callback;
import ssh.SshLibrary.ssh_auth_password_callback;
import ssh.SshLibrary.ssh_auth_pubkey_callback;
import ssh.SshLibrary.ssh_channel_open_request_session_callback;
import ssh.SshLibrary.ssh_gssapi_accept_sec_ctx_callback;
import ssh.SshLibrary.ssh_gssapi_select_oid_callback;
import ssh.SshLibrary.ssh_gssapi_verify_mic_callback;
import ssh.SshLibrary.ssh_service_request_callback;
/**
 * This structure can be used to implement a libssh server, with appropriate callbacks.<br>
 * <i>native declaration : /usr/include/libssh/callbacks.h:205</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ssh_server_callbacks_struct extends Structure {
	public SizeT size;
	/** C type : void* */
	public Pointer userdata;
	/** C type : ssh_auth_password_callback */
	public ssh_auth_password_callback auth_password_function;
	/** C type : ssh_auth_none_callback */
	public ssh_auth_none_callback auth_none_function;
	/** C type : ssh_auth_gssapi_mic_callback */
	public ssh_auth_gssapi_mic_callback auth_gssapi_mic_function;
	/** C type : ssh_auth_pubkey_callback */
	public ssh_auth_pubkey_callback auth_pubkey_function;
	/** C type : ssh_service_request_callback */
	public ssh_service_request_callback service_request_function;
	/** C type : ssh_channel_open_request_session_callback */
	public ssh_channel_open_request_session_callback channel_open_request_session_function;
	/** C type : ssh_gssapi_select_oid_callback */
	public ssh_gssapi_select_oid_callback gssapi_select_oid_function;
	/** C type : ssh_gssapi_accept_sec_ctx_callback */
	public ssh_gssapi_accept_sec_ctx_callback gssapi_accept_sec_ctx_function;
	/** C type : ssh_gssapi_verify_mic_callback */
	public ssh_gssapi_verify_mic_callback gssapi_verify_mic_function;
	public ssh_server_callbacks_struct() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("size", "userdata", "auth_password_function", "auth_none_function", "auth_gssapi_mic_function", "auth_pubkey_function", "service_request_function", "channel_open_request_session_function", "gssapi_select_oid_function", "gssapi_accept_sec_ctx_function", "gssapi_verify_mic_function");
	}
	public ssh_server_callbacks_struct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ssh_server_callbacks_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends ssh_server_callbacks_struct implements Structure.ByValue {
		
	};
}
