__LINE__=__LINE__
__FILE__=__FILE__
__COUNTER__=__COUNTER__
__cplusplus=__cplusplus => 1
__LITTLE_ENDIAN__=__LITTLE_ENDIAN__ => 1
G_BYTE_ORDER=G_BYTE_ORDER => 1234
NDEBUG=NDEBUG => 1
__STDC__=__STDC__ => 1
HAVE_PROTOTYPES=HAVE_PROTOTYPES => 1
STDC_HEADERS=STDC_HEADERS => 1
__GNUC__=__GNUC__ => 1
TARGET_CPU_X86_64=TARGET_CPU_X86_64 => 1
__i386__=__i386__ => 1
__x86_64__=__x86_64__ => 1
__amd64__=__amd64__ => 1
M_I86=M_I86 => 1
_M_I86=_M_I86 => 1
_WIN32=_WIN32 => 1
__attribute__=__attribute__(xyz)
_LIBSSH_H=_LIBSSH_H
LIBSSH_API=LIBSSH_API => __attribute__((dllimport))
_UNISTD_H=_UNISTD_H => 1
_FEATURES_H=_FEATURES_H => 1
__KERNEL_STRICT_NAMES=__KERNEL_STRICT_NAMES
__GNUC_PREREQ=__GNUC_PREREQ(maj, min) => 0
__glibc_clang_prereq=__glibc_clang_prereq(maj, min) => 0
__GLIBC_USE=__GLIBC_USE(F) => __GLIBC_USE_ ## F
_DEFAULT_SOURCE=_DEFAULT_SOURCE => 1
__USE_POSIX_IMPLICITLY=__USE_POSIX_IMPLICITLY => 1
_POSIX_SOURCE=_POSIX_SOURCE => 1
_POSIX_C_SOURCE=_POSIX_C_SOURCE => 200809L
__USE_POSIX=__USE_POSIX => 1
__USE_POSIX2=__USE_POSIX2 => 1
__USE_POSIX199309=__USE_POSIX199309 => 1
__USE_POSIX199506=__USE_POSIX199506 => 1
__USE_XOPEN2K=__USE_XOPEN2K => 1
__USE_ISOC95=__USE_ISOC95 => 1
__USE_ISOC99=__USE_ISOC99 => 1
__USE_XOPEN2K8=__USE_XOPEN2K8 => 1
_ATFILE_SOURCE=_ATFILE_SOURCE => 1
__USE_MISC=__USE_MISC => 1
__USE_ATFILE=__USE_ATFILE => 1
__USE_FORTIFY_LEVEL=__USE_FORTIFY_LEVEL => 0
__GLIBC_USE_DEPRECATED_GETS=__GLIBC_USE_DEPRECATED_GETS => 1
_STDC_PREDEF_H=_STDC_PREDEF_H => 1
__STDC_IEC_559__=__STDC_IEC_559__ => 1
__STDC_IEC_559_COMPLEX__=__STDC_IEC_559_COMPLEX__ => 1
__STDC_ISO_10646__=__STDC_ISO_10646__ => 201706L
__STDC_NO_THREADS__=__STDC_NO_THREADS__ => 1
__GNU_LIBRARY__=__GNU_LIBRARY__ => 6
__GLIBC__=__GLIBC__ => 2
__GLIBC_MINOR__=__GLIBC_MINOR__ => 27
__GLIBC_PREREQ=__GLIBC_PREREQ(maj, min) => ((__GLIBC__ << 16) + __GLIBC_MINOR__ >= ((maj) << 16) + (min))
_SYS_CDEFS_H=_SYS_CDEFS_H => 1
__LEAF=__LEAF
__LEAF_ATTR=__LEAF_ATTR
__THROW=__THROW
__THROWNL=__THROWNL
__NTH=__NTH(fct) => fct
__NTHNL=__NTHNL(fct) => fct
__glibc_clang_has_extension=__glibc_clang_has_extension(ext) => 0
__P=__P(args) => args
__PMT=__PMT(args) => args
__CONCAT=__CONCAT(x, y) => x ## y
__STRING=__STRING(x) => #x
__ptr_t=__ptr_t => void *
__BEGIN_DECLS=__BEGIN_DECLS => extern "C" {
__END_DECLS=__END_DECLS => }
__bos=__bos(ptr) => __builtin_object_size (ptr, __USE_FORTIFY_LEVEL > 1)
__bos0=__bos0(ptr) => __builtin_object_size (ptr, 0)
__warndecl=__warndecl(name, msg) => extern void name (void)
__warnattr=__warnattr(msg)
__errordecl=__errordecl(name, msg) => extern void name (void)
__flexarr=__flexarr => [0]
__glibc_c99_flexarr_available=__glibc_c99_flexarr_available => 1
__attribute_malloc__=__attribute_malloc__
__attribute_alloc_size__=__attribute_alloc_size__(params)
__attribute_pure__=__attribute_pure__
__attribute_const__=__attribute_const__
__attribute_used__=__attribute_used__ => __attribute__ ((__unused__))
__attribute_noinline__=__attribute_noinline__
__attribute_deprecated__=__attribute_deprecated__
__attribute_deprecated_msg__=__attribute_deprecated_msg__(msg) => __attribute_deprecated__
__attribute_format_arg__=__attribute_format_arg__(x)
__attribute_format_strfmon__=__attribute_format_strfmon__(a, b)
__nonnull=__nonnull(params)
__attribute_warn_unused_result__=__attribute_warn_unused_result__
__wur=__wur
__always_inline=__always_inline => __inline
__attribute_artificial__=__attribute_artificial__
__extension__=__extension__
__restrict=__restrict
__restrict_arr=__restrict_arr
__glibc_unlikely=__glibc_unlikely(cond) => (cond)
__glibc_likely=__glibc_likely(cond) => (cond)
__attribute_nonstring__=__attribute_nonstring__
__WORDSIZE=__WORDSIZE => 64
__WORDSIZE_TIME64_COMPAT32=__WORDSIZE_TIME64_COMPAT32 => 1
__SYSCALL_WORDSIZE=__SYSCALL_WORDSIZE => 64
__LDBL_REDIR1=__LDBL_REDIR1(name, proto, alias) => name proto
__LDBL_REDIR=__LDBL_REDIR(name, proto) => name proto
__LDBL_REDIR1_NTH=__LDBL_REDIR1_NTH(name, proto, alias) => name proto __THROW
__LDBL_REDIR_NTH=__LDBL_REDIR_NTH(name, proto) => name proto __THROW
__LDBL_REDIR_DECL=__LDBL_REDIR_DECL(name)
__glibc_macro_warning=__glibc_macro_warning(msg)
__HAVE_GENERIC_SELECTION=__HAVE_GENERIC_SELECTION => 0
_POSIX_VERSION=_POSIX_VERSION => 200809L
__POSIX2_THIS_VERSION=__POSIX2_THIS_VERSION => 200809L
_POSIX2_VERSION=_POSIX2_VERSION => __POSIX2_THIS_VERSION
_POSIX2_C_VERSION=_POSIX2_C_VERSION => __POSIX2_THIS_VERSION
_POSIX2_C_BIND=_POSIX2_C_BIND => __POSIX2_THIS_VERSION
_POSIX2_C_DEV=_POSIX2_C_DEV => __POSIX2_THIS_VERSION
_POSIX2_SW_DEV=_POSIX2_SW_DEV => __POSIX2_THIS_VERSION
_POSIX2_LOCALEDEF=_POSIX2_LOCALEDEF => __POSIX2_THIS_VERSION
_XOPEN_VERSION=_XOPEN_VERSION => 700
_XOPEN_XCU_VERSION=_XOPEN_XCU_VERSION => 4
_XOPEN_XPG2=_XOPEN_XPG2 => 1
_XOPEN_XPG3=_XOPEN_XPG3 => 1
_XOPEN_XPG4=_XOPEN_XPG4 => 1
_XOPEN_UNIX=_XOPEN_UNIX => 1
_XOPEN_CRYPT=_XOPEN_CRYPT => 1
_XOPEN_ENH_I18N=_XOPEN_ENH_I18N => 1
_XOPEN_LEGACY=_XOPEN_LEGACY => 1
_BITS_POSIX_OPT_H=_BITS_POSIX_OPT_H => 1
_POSIX_JOB_CONTROL=_POSIX_JOB_CONTROL => 1
_POSIX_SAVED_IDS=_POSIX_SAVED_IDS => 1
_POSIX_PRIORITY_SCHEDULING=_POSIX_PRIORITY_SCHEDULING => 200809L
_POSIX_SYNCHRONIZED_IO=_POSIX_SYNCHRONIZED_IO => 200809L
_POSIX_FSYNC=_POSIX_FSYNC => 200809L
_POSIX_MAPPED_FILES=_POSIX_MAPPED_FILES => 200809L
_POSIX_MEMLOCK=_POSIX_MEMLOCK => 200809L
_POSIX_MEMLOCK_RANGE=_POSIX_MEMLOCK_RANGE => 200809L
_POSIX_MEMORY_PROTECTION=_POSIX_MEMORY_PROTECTION => 200809L
_POSIX_CHOWN_RESTRICTED=_POSIX_CHOWN_RESTRICTED => 0
_POSIX_VDISABLE=_POSIX_VDISABLE => '\0'
_POSIX_NO_TRUNC=_POSIX_NO_TRUNC => 1
_XOPEN_REALTIME=_XOPEN_REALTIME => 1
_XOPEN_REALTIME_THREADS=_XOPEN_REALTIME_THREADS => 1
_XOPEN_SHM=_XOPEN_SHM => 1
_POSIX_THREADS=_POSIX_THREADS => 200809L
_POSIX_REENTRANT_FUNCTIONS=_POSIX_REENTRANT_FUNCTIONS => 1
_POSIX_THREAD_SAFE_FUNCTIONS=_POSIX_THREAD_SAFE_FUNCTIONS => 200809L
_POSIX_THREAD_PRIORITY_SCHEDULING=_POSIX_THREAD_PRIORITY_SCHEDULING => 200809L
_POSIX_THREAD_ATTR_STACKSIZE=_POSIX_THREAD_ATTR_STACKSIZE => 200809L
_POSIX_THREAD_ATTR_STACKADDR=_POSIX_THREAD_ATTR_STACKADDR => 200809L
_POSIX_THREAD_PRIO_INHERIT=_POSIX_THREAD_PRIO_INHERIT => 200809L
_POSIX_THREAD_PRIO_PROTECT=_POSIX_THREAD_PRIO_PROTECT => 200809L
_POSIX_THREAD_ROBUST_PRIO_INHERIT=_POSIX_THREAD_ROBUST_PRIO_INHERIT => 200809L
_POSIX_THREAD_ROBUST_PRIO_PROTECT=_POSIX_THREAD_ROBUST_PRIO_PROTECT => -1
_POSIX_SEMAPHORES=_POSIX_SEMAPHORES => 200809L
_POSIX_REALTIME_SIGNALS=_POSIX_REALTIME_SIGNALS => 200809L
_POSIX_ASYNCHRONOUS_IO=_POSIX_ASYNCHRONOUS_IO => 200809L
_POSIX_ASYNC_IO=_POSIX_ASYNC_IO => 1
_LFS_ASYNCHRONOUS_IO=_LFS_ASYNCHRONOUS_IO => 1
_POSIX_PRIORITIZED_IO=_POSIX_PRIORITIZED_IO => 200809L
_LFS64_ASYNCHRONOUS_IO=_LFS64_ASYNCHRONOUS_IO => 1
_LFS_LARGEFILE=_LFS_LARGEFILE => 1
_LFS64_LARGEFILE=_LFS64_LARGEFILE => 1
_LFS64_STDIO=_LFS64_STDIO => 1
_POSIX_SHARED_MEMORY_OBJECTS=_POSIX_SHARED_MEMORY_OBJECTS => 200809L
_POSIX_CPUTIME=_POSIX_CPUTIME => 0
_POSIX_THREAD_CPUTIME=_POSIX_THREAD_CPUTIME => 0
_POSIX_REGEXP=_POSIX_REGEXP => 1
_POSIX_READER_WRITER_LOCKS=_POSIX_READER_WRITER_LOCKS => 200809L
_POSIX_SHELL=_POSIX_SHELL => 1
_POSIX_TIMEOUTS=_POSIX_TIMEOUTS => 200809L
_POSIX_SPIN_LOCKS=_POSIX_SPIN_LOCKS => 200809L
_POSIX_SPAWN=_POSIX_SPAWN => 200809L
_POSIX_TIMERS=_POSIX_TIMERS => 200809L
_POSIX_BARRIERS=_POSIX_BARRIERS => 200809L
_POSIX_MESSAGE_PASSING=_POSIX_MESSAGE_PASSING => 200809L
_POSIX_THREAD_PROCESS_SHARED=_POSIX_THREAD_PROCESS_SHARED => 200809L
_POSIX_MONOTONIC_CLOCK=_POSIX_MONOTONIC_CLOCK => 0
_POSIX_CLOCK_SELECTION=_POSIX_CLOCK_SELECTION => 200809L
_POSIX_ADVISORY_INFO=_POSIX_ADVISORY_INFO => 200809L
_POSIX_IPV6=_POSIX_IPV6 => 200809L
_POSIX_RAW_SOCKETS=_POSIX_RAW_SOCKETS => 200809L
_POSIX2_CHAR_TERM=_POSIX2_CHAR_TERM => 200809L
_POSIX_SPORADIC_SERVER=_POSIX_SPORADIC_SERVER => -1
_POSIX_THREAD_SPORADIC_SERVER=_POSIX_THREAD_SPORADIC_SERVER => -1
_POSIX_TRACE=_POSIX_TRACE => -1
_POSIX_TRACE_EVENT_FILTER=_POSIX_TRACE_EVENT_FILTER => -1
_POSIX_TRACE_INHERIT=_POSIX_TRACE_INHERIT => -1
_POSIX_TRACE_LOG=_POSIX_TRACE_LOG => -1
_POSIX_TYPED_MEMORY_OBJECTS=_POSIX_TYPED_MEMORY_OBJECTS => -1
_POSIX_V7_LPBIG_OFFBIG=_POSIX_V7_LPBIG_OFFBIG => -1
_POSIX_V6_LPBIG_OFFBIG=_POSIX_V6_LPBIG_OFFBIG => -1
_XBS5_LPBIG_OFFBIG=_XBS5_LPBIG_OFFBIG => -1
_POSIX_V7_LP64_OFF64=_POSIX_V7_LP64_OFF64 => 1
_POSIX_V6_LP64_OFF64=_POSIX_V6_LP64_OFF64 => 1
_XBS5_LP64_OFF64=_XBS5_LP64_OFF64 => 1
__ILP32_OFF32_CFLAGS=__ILP32_OFF32_CFLAGS => "-m32"
__ILP32_OFF32_LDFLAGS=__ILP32_OFF32_LDFLAGS => "-m32"
__ILP32_OFFBIG_CFLAGS=__ILP32_OFFBIG_CFLAGS => "-m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
__ILP32_OFFBIG_LDFLAGS=__ILP32_OFFBIG_LDFLAGS => "-m32"
__LP64_OFF64_CFLAGS=__LP64_OFF64_CFLAGS => "-m64"
__LP64_OFF64_LDFLAGS=__LP64_OFF64_LDFLAGS => "-m64"
STDIN_FILENO=STDIN_FILENO => 0
STDOUT_FILENO=STDOUT_FILENO => 1
STDERR_FILENO=STDERR_FILENO => 2
_BITS_TYPES_H=_BITS_TYPES_H => 1
__S16_TYPE=__S16_TYPE => short int
__U16_TYPE=__U16_TYPE => unsigned short int
__S32_TYPE=__S32_TYPE => int
__U32_TYPE=__U32_TYPE => unsigned int
__SLONGWORD_TYPE=__SLONGWORD_TYPE => long int
__ULONGWORD_TYPE=__ULONGWORD_TYPE => unsigned long int
__SQUAD_TYPE=__SQUAD_TYPE => long int
__UQUAD_TYPE=__UQUAD_TYPE => unsigned long int
__SWORD_TYPE=__SWORD_TYPE => long int
__UWORD_TYPE=__UWORD_TYPE => unsigned long int
__SLONG32_TYPE=__SLONG32_TYPE => int
__ULONG32_TYPE=__ULONG32_TYPE => unsigned int
__S64_TYPE=__S64_TYPE => long int
__U64_TYPE=__U64_TYPE => unsigned long int
_BITS_TYPESIZES_H=_BITS_TYPESIZES_H => 1
__SYSCALL_SLONG_TYPE=__SYSCALL_SLONG_TYPE => __SLONGWORD_TYPE
__SYSCALL_ULONG_TYPE=__SYSCALL_ULONG_TYPE => __ULONGWORD_TYPE
__DEV_T_TYPE=__DEV_T_TYPE => __UQUAD_TYPE
__UID_T_TYPE=__UID_T_TYPE => __U32_TYPE
__GID_T_TYPE=__GID_T_TYPE => __U32_TYPE
__INO_T_TYPE=__INO_T_TYPE => __SYSCALL_ULONG_TYPE
__INO64_T_TYPE=__INO64_T_TYPE => __UQUAD_TYPE
__MODE_T_TYPE=__MODE_T_TYPE => __U32_TYPE
__NLINK_T_TYPE=__NLINK_T_TYPE => __SYSCALL_ULONG_TYPE
__FSWORD_T_TYPE=__FSWORD_T_TYPE => __SYSCALL_SLONG_TYPE
__OFF_T_TYPE=__OFF_T_TYPE => __SYSCALL_SLONG_TYPE
__OFF64_T_TYPE=__OFF64_T_TYPE => __SQUAD_TYPE
__PID_T_TYPE=__PID_T_TYPE => __S32_TYPE
__RLIM_T_TYPE=__RLIM_T_TYPE => __SYSCALL_ULONG_TYPE
__RLIM64_T_TYPE=__RLIM64_T_TYPE => __UQUAD_TYPE
__BLKCNT_T_TYPE=__BLKCNT_T_TYPE => __SYSCALL_SLONG_TYPE
__BLKCNT64_T_TYPE=__BLKCNT64_T_TYPE => __SQUAD_TYPE
__FSBLKCNT_T_TYPE=__FSBLKCNT_T_TYPE => __SYSCALL_ULONG_TYPE
__FSBLKCNT64_T_TYPE=__FSBLKCNT64_T_TYPE => __UQUAD_TYPE
__FSFILCNT_T_TYPE=__FSFILCNT_T_TYPE => __SYSCALL_ULONG_TYPE
__FSFILCNT64_T_TYPE=__FSFILCNT64_T_TYPE => __UQUAD_TYPE
__ID_T_TYPE=__ID_T_TYPE => __U32_TYPE
__CLOCK_T_TYPE=__CLOCK_T_TYPE => __SYSCALL_SLONG_TYPE
__TIME_T_TYPE=__TIME_T_TYPE => __SYSCALL_SLONG_TYPE
__USECONDS_T_TYPE=__USECONDS_T_TYPE => __U32_TYPE
__SUSECONDS_T_TYPE=__SUSECONDS_T_TYPE => __SYSCALL_SLONG_TYPE
__DADDR_T_TYPE=__DADDR_T_TYPE => __S32_TYPE
__KEY_T_TYPE=__KEY_T_TYPE => __S32_TYPE
__CLOCKID_T_TYPE=__CLOCKID_T_TYPE => __S32_TYPE
__TIMER_T_TYPE=__TIMER_T_TYPE => void *
__BLKSIZE_T_TYPE=__BLKSIZE_T_TYPE => __SYSCALL_SLONG_TYPE
__FSID_T_TYPE=__FSID_T_TYPE => struct { int __val[2]; }
__SSIZE_T_TYPE=__SSIZE_T_TYPE => __SWORD_TYPE
__CPU_MASK_TYPE=__CPU_MASK_TYPE => __SYSCALL_ULONG_TYPE
__OFF_T_MATCHES_OFF64_T=__OFF_T_MATCHES_OFF64_T => 1
__INO_T_MATCHES_INO64_T=__INO_T_MATCHES_INO64_T => 1
__RLIM_T_MATCHES_RLIM64_T=__RLIM_T_MATCHES_RLIM64_T => 1
__FD_SETSIZE=__FD_SETSIZE => 1024
__ssize_t_defined=__ssize_t_defined
__need_size_t=__need_size_t
__need_NULL=__need_NULL
__gid_t_defined=__gid_t_defined
__uid_t_defined=__uid_t_defined
__off_t_defined=__off_t_defined
__useconds_t_defined=__useconds_t_defined
__pid_t_defined=__pid_t_defined
__intptr_t_defined=__intptr_t_defined
__socklen_t_defined=__socklen_t_defined
R_OK=R_OK => 4
W_OK=W_OK => 2
X_OK=X_OK => 1
F_OK=F_OK => 0
SEEK_SET=SEEK_SET => 0
SEEK_CUR=SEEK_CUR => 1
SEEK_END=SEEK_END => 2
L_SET=L_SET => SEEK_SET
L_INCR=L_INCR => SEEK_CUR
L_XTND=L_XTND => SEEK_END
_PC_LINK_MAX=_PC_LINK_MAX => _PC_LINK_MAX
_PC_MAX_CANON=_PC_MAX_CANON => _PC_MAX_CANON
_PC_MAX_INPUT=_PC_MAX_INPUT => _PC_MAX_INPUT
_PC_NAME_MAX=_PC_NAME_MAX => _PC_NAME_MAX
_PC_PATH_MAX=_PC_PATH_MAX => _PC_PATH_MAX
_PC_PIPE_BUF=_PC_PIPE_BUF => _PC_PIPE_BUF
_PC_CHOWN_RESTRICTED=_PC_CHOWN_RESTRICTED => _PC_CHOWN_RESTRICTED
_PC_NO_TRUNC=_PC_NO_TRUNC => _PC_NO_TRUNC
_PC_VDISABLE=_PC_VDISABLE => _PC_VDISABLE
_PC_SYNC_IO=_PC_SYNC_IO => _PC_SYNC_IO
_PC_ASYNC_IO=_PC_ASYNC_IO => _PC_ASYNC_IO
_PC_PRIO_IO=_PC_PRIO_IO => _PC_PRIO_IO
_PC_SOCK_MAXBUF=_PC_SOCK_MAXBUF => _PC_SOCK_MAXBUF
_PC_FILESIZEBITS=_PC_FILESIZEBITS => _PC_FILESIZEBITS
_PC_REC_INCR_XFER_SIZE=_PC_REC_INCR_XFER_SIZE => _PC_REC_INCR_XFER_SIZE
_PC_REC_MAX_XFER_SIZE=_PC_REC_MAX_XFER_SIZE => _PC_REC_MAX_XFER_SIZE
_PC_REC_MIN_XFER_SIZE=_PC_REC_MIN_XFER_SIZE => _PC_REC_MIN_XFER_SIZE
_PC_REC_XFER_ALIGN=_PC_REC_XFER_ALIGN => _PC_REC_XFER_ALIGN
_PC_ALLOC_SIZE_MIN=_PC_ALLOC_SIZE_MIN => _PC_ALLOC_SIZE_MIN
_PC_SYMLINK_MAX=_PC_SYMLINK_MAX => _PC_SYMLINK_MAX
_PC_2_SYMLINKS=_PC_2_SYMLINKS => _PC_2_SYMLINKS
_SC_ARG_MAX=_SC_ARG_MAX => _SC_ARG_MAX
_SC_CHILD_MAX=_SC_CHILD_MAX => _SC_CHILD_MAX
_SC_CLK_TCK=_SC_CLK_TCK => _SC_CLK_TCK
_SC_NGROUPS_MAX=_SC_NGROUPS_MAX => _SC_NGROUPS_MAX
_SC_OPEN_MAX=_SC_OPEN_MAX => _SC_OPEN_MAX
_SC_STREAM_MAX=_SC_STREAM_MAX => _SC_STREAM_MAX
_SC_TZNAME_MAX=_SC_TZNAME_MAX => _SC_TZNAME_MAX
_SC_JOB_CONTROL=_SC_JOB_CONTROL => _SC_JOB_CONTROL
_SC_SAVED_IDS=_SC_SAVED_IDS => _SC_SAVED_IDS
_SC_REALTIME_SIGNALS=_SC_REALTIME_SIGNALS => _SC_REALTIME_SIGNALS
_SC_PRIORITY_SCHEDULING=_SC_PRIORITY_SCHEDULING => _SC_PRIORITY_SCHEDULING
_SC_TIMERS=_SC_TIMERS => _SC_TIMERS
_SC_ASYNCHRONOUS_IO=_SC_ASYNCHRONOUS_IO => _SC_ASYNCHRONOUS_IO
_SC_PRIORITIZED_IO=_SC_PRIORITIZED_IO => _SC_PRIORITIZED_IO
_SC_SYNCHRONIZED_IO=_SC_SYNCHRONIZED_IO => _SC_SYNCHRONIZED_IO
_SC_FSYNC=_SC_FSYNC => _SC_FSYNC
_SC_MAPPED_FILES=_SC_MAPPED_FILES => _SC_MAPPED_FILES
_SC_MEMLOCK=_SC_MEMLOCK => _SC_MEMLOCK
_SC_MEMLOCK_RANGE=_SC_MEMLOCK_RANGE => _SC_MEMLOCK_RANGE
_SC_MEMORY_PROTECTION=_SC_MEMORY_PROTECTION => _SC_MEMORY_PROTECTION
_SC_MESSAGE_PASSING=_SC_MESSAGE_PASSING => _SC_MESSAGE_PASSING
_SC_SEMAPHORES=_SC_SEMAPHORES => _SC_SEMAPHORES
_SC_SHARED_MEMORY_OBJECTS=_SC_SHARED_MEMORY_OBJECTS => _SC_SHARED_MEMORY_OBJECTS
_SC_AIO_LISTIO_MAX=_SC_AIO_LISTIO_MAX => _SC_AIO_LISTIO_MAX
_SC_AIO_MAX=_SC_AIO_MAX => _SC_AIO_MAX
_SC_AIO_PRIO_DELTA_MAX=_SC_AIO_PRIO_DELTA_MAX => _SC_AIO_PRIO_DELTA_MAX
_SC_DELAYTIMER_MAX=_SC_DELAYTIMER_MAX => _SC_DELAYTIMER_MAX
_SC_MQ_OPEN_MAX=_SC_MQ_OPEN_MAX => _SC_MQ_OPEN_MAX
_SC_MQ_PRIO_MAX=_SC_MQ_PRIO_MAX => _SC_MQ_PRIO_MAX
_SC_VERSION=_SC_VERSION => _SC_VERSION
_SC_PAGESIZE=_SC_PAGESIZE => _SC_PAGESIZE
_SC_PAGE_SIZE=_SC_PAGE_SIZE => _SC_PAGESIZE
_SC_RTSIG_MAX=_SC_RTSIG_MAX => _SC_RTSIG_MAX
_SC_SEM_NSEMS_MAX=_SC_SEM_NSEMS_MAX => _SC_SEM_NSEMS_MAX
_SC_SEM_VALUE_MAX=_SC_SEM_VALUE_MAX => _SC_SEM_VALUE_MAX
_SC_SIGQUEUE_MAX=_SC_SIGQUEUE_MAX => _SC_SIGQUEUE_MAX
_SC_TIMER_MAX=_SC_TIMER_MAX => _SC_TIMER_MAX
_SC_BC_BASE_MAX=_SC_BC_BASE_MAX => _SC_BC_BASE_MAX
_SC_BC_DIM_MAX=_SC_BC_DIM_MAX => _SC_BC_DIM_MAX
_SC_BC_SCALE_MAX=_SC_BC_SCALE_MAX => _SC_BC_SCALE_MAX
_SC_BC_STRING_MAX=_SC_BC_STRING_MAX => _SC_BC_STRING_MAX
_SC_COLL_WEIGHTS_MAX=_SC_COLL_WEIGHTS_MAX => _SC_COLL_WEIGHTS_MAX
_SC_EQUIV_CLASS_MAX=_SC_EQUIV_CLASS_MAX => _SC_EQUIV_CLASS_MAX
_SC_EXPR_NEST_MAX=_SC_EXPR_NEST_MAX => _SC_EXPR_NEST_MAX
_SC_LINE_MAX=_SC_LINE_MAX => _SC_LINE_MAX
_SC_RE_DUP_MAX=_SC_RE_DUP_MAX => _SC_RE_DUP_MAX
_SC_CHARCLASS_NAME_MAX=_SC_CHARCLASS_NAME_MAX => _SC_CHARCLASS_NAME_MAX
_SC_2_VERSION=_SC_2_VERSION => _SC_2_VERSION
_SC_2_C_BIND=_SC_2_C_BIND => _SC_2_C_BIND
_SC_2_C_DEV=_SC_2_C_DEV => _SC_2_C_DEV
_SC_2_FORT_DEV=_SC_2_FORT_DEV => _SC_2_FORT_DEV
_SC_2_FORT_RUN=_SC_2_FORT_RUN => _SC_2_FORT_RUN
_SC_2_SW_DEV=_SC_2_SW_DEV => _SC_2_SW_DEV
_SC_2_LOCALEDEF=_SC_2_LOCALEDEF => _SC_2_LOCALEDEF
_SC_PII=_SC_PII => _SC_PII
_SC_PII_XTI=_SC_PII_XTI => _SC_PII_XTI
_SC_PII_SOCKET=_SC_PII_SOCKET => _SC_PII_SOCKET
_SC_PII_INTERNET=_SC_PII_INTERNET => _SC_PII_INTERNET
_SC_PII_OSI=_SC_PII_OSI => _SC_PII_OSI
_SC_POLL=_SC_POLL => _SC_POLL
_SC_SELECT=_SC_SELECT => _SC_SELECT
_SC_UIO_MAXIOV=_SC_UIO_MAXIOV => _SC_UIO_MAXIOV
_SC_IOV_MAX=_SC_IOV_MAX => _SC_IOV_MAX
_SC_PII_INTERNET_STREAM=_SC_PII_INTERNET_STREAM => _SC_PII_INTERNET_STREAM
_SC_PII_INTERNET_DGRAM=_SC_PII_INTERNET_DGRAM => _SC_PII_INTERNET_DGRAM
_SC_PII_OSI_COTS=_SC_PII_OSI_COTS => _SC_PII_OSI_COTS
_SC_PII_OSI_CLTS=_SC_PII_OSI_CLTS => _SC_PII_OSI_CLTS
_SC_PII_OSI_M=_SC_PII_OSI_M => _SC_PII_OSI_M
_SC_T_IOV_MAX=_SC_T_IOV_MAX => _SC_T_IOV_MAX
_SC_THREADS=_SC_THREADS => _SC_THREADS
_SC_THREAD_SAFE_FUNCTIONS=_SC_THREAD_SAFE_FUNCTIONS => _SC_THREAD_SAFE_FUNCTIONS
_SC_GETGR_R_SIZE_MAX=_SC_GETGR_R_SIZE_MAX => _SC_GETGR_R_SIZE_MAX
_SC_GETPW_R_SIZE_MAX=_SC_GETPW_R_SIZE_MAX => _SC_GETPW_R_SIZE_MAX
_SC_LOGIN_NAME_MAX=_SC_LOGIN_NAME_MAX => _SC_LOGIN_NAME_MAX
_SC_TTY_NAME_MAX=_SC_TTY_NAME_MAX => _SC_TTY_NAME_MAX
_SC_THREAD_DESTRUCTOR_ITERATIONS=_SC_THREAD_DESTRUCTOR_ITERATIONS => _SC_THREAD_DESTRUCTOR_ITERATIONS
_SC_THREAD_KEYS_MAX=_SC_THREAD_KEYS_MAX => _SC_THREAD_KEYS_MAX
_SC_THREAD_STACK_MIN=_SC_THREAD_STACK_MIN => _SC_THREAD_STACK_MIN
_SC_THREAD_THREADS_MAX=_SC_THREAD_THREADS_MAX => _SC_THREAD_THREADS_MAX
_SC_THREAD_ATTR_STACKADDR=_SC_THREAD_ATTR_STACKADDR => _SC_THREAD_ATTR_STACKADDR
_SC_THREAD_ATTR_STACKSIZE=_SC_THREAD_ATTR_STACKSIZE => _SC_THREAD_ATTR_STACKSIZE
_SC_THREAD_PRIORITY_SCHEDULING=_SC_THREAD_PRIORITY_SCHEDULING => _SC_THREAD_PRIORITY_SCHEDULING
_SC_THREAD_PRIO_INHERIT=_SC_THREAD_PRIO_INHERIT => _SC_THREAD_PRIO_INHERIT
_SC_THREAD_PRIO_PROTECT=_SC_THREAD_PRIO_PROTECT => _SC_THREAD_PRIO_PROTECT
_SC_THREAD_PROCESS_SHARED=_SC_THREAD_PROCESS_SHARED => _SC_THREAD_PROCESS_SHARED
_SC_NPROCESSORS_CONF=_SC_NPROCESSORS_CONF => _SC_NPROCESSORS_CONF
_SC_NPROCESSORS_ONLN=_SC_NPROCESSORS_ONLN => _SC_NPROCESSORS_ONLN
_SC_PHYS_PAGES=_SC_PHYS_PAGES => _SC_PHYS_PAGES
_SC_AVPHYS_PAGES=_SC_AVPHYS_PAGES => _SC_AVPHYS_PAGES
_SC_ATEXIT_MAX=_SC_ATEXIT_MAX => _SC_ATEXIT_MAX
_SC_PASS_MAX=_SC_PASS_MAX => _SC_PASS_MAX
_SC_XOPEN_VERSION=_SC_XOPEN_VERSION => _SC_XOPEN_VERSION
_SC_XOPEN_XCU_VERSION=_SC_XOPEN_XCU_VERSION => _SC_XOPEN_XCU_VERSION
_SC_XOPEN_UNIX=_SC_XOPEN_UNIX => _SC_XOPEN_UNIX
_SC_XOPEN_CRYPT=_SC_XOPEN_CRYPT => _SC_XOPEN_CRYPT
_SC_XOPEN_ENH_I18N=_SC_XOPEN_ENH_I18N => _SC_XOPEN_ENH_I18N
_SC_XOPEN_SHM=_SC_XOPEN_SHM => _SC_XOPEN_SHM
_SC_2_CHAR_TERM=_SC_2_CHAR_TERM => _SC_2_CHAR_TERM
_SC_2_C_VERSION=_SC_2_C_VERSION => _SC_2_C_VERSION
_SC_2_UPE=_SC_2_UPE => _SC_2_UPE
_SC_XOPEN_XPG2=_SC_XOPEN_XPG2 => _SC_XOPEN_XPG2
_SC_XOPEN_XPG3=_SC_XOPEN_XPG3 => _SC_XOPEN_XPG3
_SC_XOPEN_XPG4=_SC_XOPEN_XPG4 => _SC_XOPEN_XPG4
_SC_CHAR_BIT=_SC_CHAR_BIT => _SC_CHAR_BIT
_SC_CHAR_MAX=_SC_CHAR_MAX => _SC_CHAR_MAX
_SC_CHAR_MIN=_SC_CHAR_MIN => _SC_CHAR_MIN
_SC_INT_MAX=_SC_INT_MAX => _SC_INT_MAX
_SC_INT_MIN=_SC_INT_MIN => _SC_INT_MIN
_SC_LONG_BIT=_SC_LONG_BIT => _SC_LONG_BIT
_SC_WORD_BIT=_SC_WORD_BIT => _SC_WORD_BIT
_SC_MB_LEN_MAX=_SC_MB_LEN_MAX => _SC_MB_LEN_MAX
_SC_NZERO=_SC_NZERO => _SC_NZERO
_SC_SSIZE_MAX=_SC_SSIZE_MAX => _SC_SSIZE_MAX
_SC_SCHAR_MAX=_SC_SCHAR_MAX => _SC_SCHAR_MAX
_SC_SCHAR_MIN=_SC_SCHAR_MIN => _SC_SCHAR_MIN
_SC_SHRT_MAX=_SC_SHRT_MAX => _SC_SHRT_MAX
_SC_SHRT_MIN=_SC_SHRT_MIN => _SC_SHRT_MIN
_SC_UCHAR_MAX=_SC_UCHAR_MAX => _SC_UCHAR_MAX
_SC_UINT_MAX=_SC_UINT_MAX => _SC_UINT_MAX
_SC_ULONG_MAX=_SC_ULONG_MAX => _SC_ULONG_MAX
_SC_USHRT_MAX=_SC_USHRT_MAX => _SC_USHRT_MAX
_SC_NL_ARGMAX=_SC_NL_ARGMAX => _SC_NL_ARGMAX
_SC_NL_LANGMAX=_SC_NL_LANGMAX => _SC_NL_LANGMAX
_SC_NL_MSGMAX=_SC_NL_MSGMAX => _SC_NL_MSGMAX
_SC_NL_NMAX=_SC_NL_NMAX => _SC_NL_NMAX
_SC_NL_SETMAX=_SC_NL_SETMAX => _SC_NL_SETMAX
_SC_NL_TEXTMAX=_SC_NL_TEXTMAX => _SC_NL_TEXTMAX
_SC_XBS5_ILP32_OFF32=_SC_XBS5_ILP32_OFF32 => _SC_XBS5_ILP32_OFF32
_SC_XBS5_ILP32_OFFBIG=_SC_XBS5_ILP32_OFFBIG => _SC_XBS5_ILP32_OFFBIG
_SC_XBS5_LP64_OFF64=_SC_XBS5_LP64_OFF64 => _SC_XBS5_LP64_OFF64
_SC_XBS5_LPBIG_OFFBIG=_SC_XBS5_LPBIG_OFFBIG => _SC_XBS5_LPBIG_OFFBIG
_SC_XOPEN_LEGACY=_SC_XOPEN_LEGACY => _SC_XOPEN_LEGACY
_SC_XOPEN_REALTIME=_SC_XOPEN_REALTIME => _SC_XOPEN_REALTIME
_SC_XOPEN_REALTIME_THREADS=_SC_XOPEN_REALTIME_THREADS => _SC_XOPEN_REALTIME_THREADS
_SC_ADVISORY_INFO=_SC_ADVISORY_INFO => _SC_ADVISORY_INFO
_SC_BARRIERS=_SC_BARRIERS => _SC_BARRIERS
_SC_BASE=_SC_BASE => _SC_BASE
_SC_C_LANG_SUPPORT=_SC_C_LANG_SUPPORT => _SC_C_LANG_SUPPORT
_SC_C_LANG_SUPPORT_R=_SC_C_LANG_SUPPORT_R => _SC_C_LANG_SUPPORT_R
_SC_CLOCK_SELECTION=_SC_CLOCK_SELECTION => _SC_CLOCK_SELECTION
_SC_CPUTIME=_SC_CPUTIME => _SC_CPUTIME
_SC_THREAD_CPUTIME=_SC_THREAD_CPUTIME => _SC_THREAD_CPUTIME
_SC_DEVICE_IO=_SC_DEVICE_IO => _SC_DEVICE_IO
_SC_DEVICE_SPECIFIC=_SC_DEVICE_SPECIFIC => _SC_DEVICE_SPECIFIC
_SC_DEVICE_SPECIFIC_R=_SC_DEVICE_SPECIFIC_R => _SC_DEVICE_SPECIFIC_R
_SC_FD_MGMT=_SC_FD_MGMT => _SC_FD_MGMT
_SC_FIFO=_SC_FIFO => _SC_FIFO
_SC_PIPE=_SC_PIPE => _SC_PIPE
_SC_FILE_ATTRIBUTES=_SC_FILE_ATTRIBUTES => _SC_FILE_ATTRIBUTES
_SC_FILE_LOCKING=_SC_FILE_LOCKING => _SC_FILE_LOCKING
_SC_FILE_SYSTEM=_SC_FILE_SYSTEM => _SC_FILE_SYSTEM
_SC_MONOTONIC_CLOCK=_SC_MONOTONIC_CLOCK => _SC_MONOTONIC_CLOCK
_SC_MULTI_PROCESS=_SC_MULTI_PROCESS => _SC_MULTI_PROCESS
_SC_SINGLE_PROCESS=_SC_SINGLE_PROCESS => _SC_SINGLE_PROCESS
_SC_NETWORKING=_SC_NETWORKING => _SC_NETWORKING
_SC_READER_WRITER_LOCKS=_SC_READER_WRITER_LOCKS => _SC_READER_WRITER_LOCKS
_SC_SPIN_LOCKS=_SC_SPIN_LOCKS => _SC_SPIN_LOCKS
_SC_REGEXP=_SC_REGEXP => _SC_REGEXP
_SC_REGEX_VERSION=_SC_REGEX_VERSION => _SC_REGEX_VERSION
_SC_SHELL=_SC_SHELL => _SC_SHELL
_SC_SIGNALS=_SC_SIGNALS => _SC_SIGNALS
_SC_SPAWN=_SC_SPAWN => _SC_SPAWN
_SC_SPORADIC_SERVER=_SC_SPORADIC_SERVER => _SC_SPORADIC_SERVER
_SC_THREAD_SPORADIC_SERVER=_SC_THREAD_SPORADIC_SERVER => _SC_THREAD_SPORADIC_SERVER
_SC_SYSTEM_DATABASE=_SC_SYSTEM_DATABASE => _SC_SYSTEM_DATABASE
_SC_SYSTEM_DATABASE_R=_SC_SYSTEM_DATABASE_R => _SC_SYSTEM_DATABASE_R
_SC_TIMEOUTS=_SC_TIMEOUTS => _SC_TIMEOUTS
_SC_TYPED_MEMORY_OBJECTS=_SC_TYPED_MEMORY_OBJECTS => _SC_TYPED_MEMORY_OBJECTS
_SC_USER_GROUPS=_SC_USER_GROUPS => _SC_USER_GROUPS
_SC_USER_GROUPS_R=_SC_USER_GROUPS_R => _SC_USER_GROUPS_R
_SC_2_PBS=_SC_2_PBS => _SC_2_PBS
_SC_2_PBS_ACCOUNTING=_SC_2_PBS_ACCOUNTING => _SC_2_PBS_ACCOUNTING
_SC_2_PBS_LOCATE=_SC_2_PBS_LOCATE => _SC_2_PBS_LOCATE
_SC_2_PBS_MESSAGE=_SC_2_PBS_MESSAGE => _SC_2_PBS_MESSAGE
_SC_2_PBS_TRACK=_SC_2_PBS_TRACK => _SC_2_PBS_TRACK
_SC_SYMLOOP_MAX=_SC_SYMLOOP_MAX => _SC_SYMLOOP_MAX
_SC_STREAMS=_SC_STREAMS => _SC_STREAMS
_SC_2_PBS_CHECKPOINT=_SC_2_PBS_CHECKPOINT => _SC_2_PBS_CHECKPOINT
_SC_V6_ILP32_OFF32=_SC_V6_ILP32_OFF32 => _SC_V6_ILP32_OFF32
_SC_V6_ILP32_OFFBIG=_SC_V6_ILP32_OFFBIG => _SC_V6_ILP32_OFFBIG
_SC_V6_LP64_OFF64=_SC_V6_LP64_OFF64 => _SC_V6_LP64_OFF64
_SC_V6_LPBIG_OFFBIG=_SC_V6_LPBIG_OFFBIG => _SC_V6_LPBIG_OFFBIG
_SC_HOST_NAME_MAX=_SC_HOST_NAME_MAX => _SC_HOST_NAME_MAX
_SC_TRACE=_SC_TRACE => _SC_TRACE
_SC_TRACE_EVENT_FILTER=_SC_TRACE_EVENT_FILTER => _SC_TRACE_EVENT_FILTER
_SC_TRACE_INHERIT=_SC_TRACE_INHERIT => _SC_TRACE_INHERIT
_SC_TRACE_LOG=_SC_TRACE_LOG => _SC_TRACE_LOG
_SC_LEVEL1_ICACHE_SIZE=_SC_LEVEL1_ICACHE_SIZE => _SC_LEVEL1_ICACHE_SIZE
_SC_LEVEL1_ICACHE_ASSOC=_SC_LEVEL1_ICACHE_ASSOC => _SC_LEVEL1_ICACHE_ASSOC
_SC_LEVEL1_ICACHE_LINESIZE=_SC_LEVEL1_ICACHE_LINESIZE => _SC_LEVEL1_ICACHE_LINESIZE
_SC_LEVEL1_DCACHE_SIZE=_SC_LEVEL1_DCACHE_SIZE => _SC_LEVEL1_DCACHE_SIZE
_SC_LEVEL1_DCACHE_ASSOC=_SC_LEVEL1_DCACHE_ASSOC => _SC_LEVEL1_DCACHE_ASSOC
_SC_LEVEL1_DCACHE_LINESIZE=_SC_LEVEL1_DCACHE_LINESIZE => _SC_LEVEL1_DCACHE_LINESIZE
_SC_LEVEL2_CACHE_SIZE=_SC_LEVEL2_CACHE_SIZE => _SC_LEVEL2_CACHE_SIZE
_SC_LEVEL2_CACHE_ASSOC=_SC_LEVEL2_CACHE_ASSOC => _SC_LEVEL2_CACHE_ASSOC
_SC_LEVEL2_CACHE_LINESIZE=_SC_LEVEL2_CACHE_LINESIZE => _SC_LEVEL2_CACHE_LINESIZE
_SC_LEVEL3_CACHE_SIZE=_SC_LEVEL3_CACHE_SIZE => _SC_LEVEL3_CACHE_SIZE
_SC_LEVEL3_CACHE_ASSOC=_SC_LEVEL3_CACHE_ASSOC => _SC_LEVEL3_CACHE_ASSOC
_SC_LEVEL3_CACHE_LINESIZE=_SC_LEVEL3_CACHE_LINESIZE => _SC_LEVEL3_CACHE_LINESIZE
_SC_LEVEL4_CACHE_SIZE=_SC_LEVEL4_CACHE_SIZE => _SC_LEVEL4_CACHE_SIZE
_SC_LEVEL4_CACHE_ASSOC=_SC_LEVEL4_CACHE_ASSOC => _SC_LEVEL4_CACHE_ASSOC
_SC_LEVEL4_CACHE_LINESIZE=_SC_LEVEL4_CACHE_LINESIZE => _SC_LEVEL4_CACHE_LINESIZE
_SC_IPV6=_SC_IPV6 => _SC_IPV6
_SC_RAW_SOCKETS=_SC_RAW_SOCKETS => _SC_RAW_SOCKETS
_SC_V7_ILP32_OFF32=_SC_V7_ILP32_OFF32 => _SC_V7_ILP32_OFF32
_SC_V7_ILP32_OFFBIG=_SC_V7_ILP32_OFFBIG => _SC_V7_ILP32_OFFBIG
_SC_V7_LP64_OFF64=_SC_V7_LP64_OFF64 => _SC_V7_LP64_OFF64
_SC_V7_LPBIG_OFFBIG=_SC_V7_LPBIG_OFFBIG => _SC_V7_LPBIG_OFFBIG
_SC_SS_REPL_MAX=_SC_SS_REPL_MAX => _SC_SS_REPL_MAX
_SC_TRACE_EVENT_NAME_MAX=_SC_TRACE_EVENT_NAME_MAX => _SC_TRACE_EVENT_NAME_MAX
_SC_TRACE_NAME_MAX=_SC_TRACE_NAME_MAX => _SC_TRACE_NAME_MAX
_SC_TRACE_SYS_MAX=_SC_TRACE_SYS_MAX => _SC_TRACE_SYS_MAX
_SC_TRACE_USER_EVENT_MAX=_SC_TRACE_USER_EVENT_MAX => _SC_TRACE_USER_EVENT_MAX
_SC_XOPEN_STREAMS=_SC_XOPEN_STREAMS => _SC_XOPEN_STREAMS
_SC_THREAD_ROBUST_PRIO_INHERIT=_SC_THREAD_ROBUST_PRIO_INHERIT => _SC_THREAD_ROBUST_PRIO_INHERIT
_SC_THREAD_ROBUST_PRIO_PROTECT=_SC_THREAD_ROBUST_PRIO_PROTECT => _SC_THREAD_ROBUST_PRIO_PROTECT
_CS_PATH=_CS_PATH => _CS_PATH
_CS_V6_WIDTH_RESTRICTED_ENVS=_CS_V6_WIDTH_RESTRICTED_ENVS => _CS_V6_WIDTH_RESTRICTED_ENVS
_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS=_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS => _CS_V6_WIDTH_RESTRICTED_ENVS
_CS_GNU_LIBC_VERSION=_CS_GNU_LIBC_VERSION => _CS_GNU_LIBC_VERSION
_CS_GNU_LIBPTHREAD_VERSION=_CS_GNU_LIBPTHREAD_VERSION => _CS_GNU_LIBPTHREAD_VERSION
_CS_V5_WIDTH_RESTRICTED_ENVS=_CS_V5_WIDTH_RESTRICTED_ENVS => _CS_V5_WIDTH_RESTRICTED_ENVS
_CS_POSIX_V5_WIDTH_RESTRICTED_ENVS=_CS_POSIX_V5_WIDTH_RESTRICTED_ENVS => _CS_V5_WIDTH_RESTRICTED_ENVS
_CS_V7_WIDTH_RESTRICTED_ENVS=_CS_V7_WIDTH_RESTRICTED_ENVS => _CS_V7_WIDTH_RESTRICTED_ENVS
_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS=_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS => _CS_V7_WIDTH_RESTRICTED_ENVS
_CS_LFS_CFLAGS=_CS_LFS_CFLAGS => _CS_LFS_CFLAGS
_CS_LFS_LDFLAGS=_CS_LFS_LDFLAGS => _CS_LFS_LDFLAGS
_CS_LFS_LIBS=_CS_LFS_LIBS => _CS_LFS_LIBS
_CS_LFS_LINTFLAGS=_CS_LFS_LINTFLAGS => _CS_LFS_LINTFLAGS
_CS_LFS64_CFLAGS=_CS_LFS64_CFLAGS => _CS_LFS64_CFLAGS
_CS_LFS64_LDFLAGS=_CS_LFS64_LDFLAGS => _CS_LFS64_LDFLAGS
_CS_LFS64_LIBS=_CS_LFS64_LIBS => _CS_LFS64_LIBS
_CS_LFS64_LINTFLAGS=_CS_LFS64_LINTFLAGS => _CS_LFS64_LINTFLAGS
_CS_XBS5_ILP32_OFF32_CFLAGS=_CS_XBS5_ILP32_OFF32_CFLAGS => _CS_XBS5_ILP32_OFF32_CFLAGS
_CS_XBS5_ILP32_OFF32_LDFLAGS=_CS_XBS5_ILP32_OFF32_LDFLAGS => _CS_XBS5_ILP32_OFF32_LDFLAGS
_CS_XBS5_ILP32_OFF32_LIBS=_CS_XBS5_ILP32_OFF32_LIBS => _CS_XBS5_ILP32_OFF32_LIBS
_CS_XBS5_ILP32_OFF32_LINTFLAGS=_CS_XBS5_ILP32_OFF32_LINTFLAGS => _CS_XBS5_ILP32_OFF32_LINTFLAGS
_CS_XBS5_ILP32_OFFBIG_CFLAGS=_CS_XBS5_ILP32_OFFBIG_CFLAGS => _CS_XBS5_ILP32_OFFBIG_CFLAGS
_CS_XBS5_ILP32_OFFBIG_LDFLAGS=_CS_XBS5_ILP32_OFFBIG_LDFLAGS => _CS_XBS5_ILP32_OFFBIG_LDFLAGS
_CS_XBS5_ILP32_OFFBIG_LIBS=_CS_XBS5_ILP32_OFFBIG_LIBS => _CS_XBS5_ILP32_OFFBIG_LIBS
_CS_XBS5_ILP32_OFFBIG_LINTFLAGS=_CS_XBS5_ILP32_OFFBIG_LINTFLAGS => _CS_XBS5_ILP32_OFFBIG_LINTFLAGS
_CS_XBS5_LP64_OFF64_CFLAGS=_CS_XBS5_LP64_OFF64_CFLAGS => _CS_XBS5_LP64_OFF64_CFLAGS
_CS_XBS5_LP64_OFF64_LDFLAGS=_CS_XBS5_LP64_OFF64_LDFLAGS => _CS_XBS5_LP64_OFF64_LDFLAGS
_CS_XBS5_LP64_OFF64_LIBS=_CS_XBS5_LP64_OFF64_LIBS => _CS_XBS5_LP64_OFF64_LIBS
_CS_XBS5_LP64_OFF64_LINTFLAGS=_CS_XBS5_LP64_OFF64_LINTFLAGS => _CS_XBS5_LP64_OFF64_LINTFLAGS
_CS_XBS5_LPBIG_OFFBIG_CFLAGS=_CS_XBS5_LPBIG_OFFBIG_CFLAGS => _CS_XBS5_LPBIG_OFFBIG_CFLAGS
_CS_XBS5_LPBIG_OFFBIG_LDFLAGS=_CS_XBS5_LPBIG_OFFBIG_LDFLAGS => _CS_XBS5_LPBIG_OFFBIG_LDFLAGS
_CS_XBS5_LPBIG_OFFBIG_LIBS=_CS_XBS5_LPBIG_OFFBIG_LIBS => _CS_XBS5_LPBIG_OFFBIG_LIBS
_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS=_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS => _CS_XBS5_LPBIG_OFFBIG_LINTFLAGS
_CS_POSIX_V6_ILP32_OFF32_CFLAGS=_CS_POSIX_V6_ILP32_OFF32_CFLAGS => _CS_POSIX_V6_ILP32_OFF32_CFLAGS
_CS_POSIX_V6_ILP32_OFF32_LDFLAGS=_CS_POSIX_V6_ILP32_OFF32_LDFLAGS => _CS_POSIX_V6_ILP32_OFF32_LDFLAGS
_CS_POSIX_V6_ILP32_OFF32_LIBS=_CS_POSIX_V6_ILP32_OFF32_LIBS => _CS_POSIX_V6_ILP32_OFF32_LIBS
_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS=_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS => _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS
_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS=_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS => _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS
_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS=_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS => _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS
_CS_POSIX_V6_ILP32_OFFBIG_LIBS=_CS_POSIX_V6_ILP32_OFFBIG_LIBS => _CS_POSIX_V6_ILP32_OFFBIG_LIBS
_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS=_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS => _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS
_CS_POSIX_V6_LP64_OFF64_CFLAGS=_CS_POSIX_V6_LP64_OFF64_CFLAGS => _CS_POSIX_V6_LP64_OFF64_CFLAGS
_CS_POSIX_V6_LP64_OFF64_LDFLAGS=_CS_POSIX_V6_LP64_OFF64_LDFLAGS => _CS_POSIX_V6_LP64_OFF64_LDFLAGS
_CS_POSIX_V6_LP64_OFF64_LIBS=_CS_POSIX_V6_LP64_OFF64_LIBS => _CS_POSIX_V6_LP64_OFF64_LIBS
_CS_POSIX_V6_LP64_OFF64_LINTFLAGS=_CS_POSIX_V6_LP64_OFF64_LINTFLAGS => _CS_POSIX_V6_LP64_OFF64_LINTFLAGS
_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS=_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS => _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS
_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS=_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS => _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS
_CS_POSIX_V6_LPBIG_OFFBIG_LIBS=_CS_POSIX_V6_LPBIG_OFFBIG_LIBS => _CS_POSIX_V6_LPBIG_OFFBIG_LIBS
_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS=_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS => _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS
_CS_POSIX_V7_ILP32_OFF32_CFLAGS=_CS_POSIX_V7_ILP32_OFF32_CFLAGS => _CS_POSIX_V7_ILP32_OFF32_CFLAGS
_CS_POSIX_V7_ILP32_OFF32_LDFLAGS=_CS_POSIX_V7_ILP32_OFF32_LDFLAGS => _CS_POSIX_V7_ILP32_OFF32_LDFLAGS
_CS_POSIX_V7_ILP32_OFF32_LIBS=_CS_POSIX_V7_ILP32_OFF32_LIBS => _CS_POSIX_V7_ILP32_OFF32_LIBS
_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS=_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS => _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS
_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS=_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS => _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS
_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS=_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS => _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS
_CS_POSIX_V7_ILP32_OFFBIG_LIBS=_CS_POSIX_V7_ILP32_OFFBIG_LIBS => _CS_POSIX_V7_ILP32_OFFBIG_LIBS
_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS=_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS => _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS
_CS_POSIX_V7_LP64_OFF64_CFLAGS=_CS_POSIX_V7_LP64_OFF64_CFLAGS => _CS_POSIX_V7_LP64_OFF64_CFLAGS
_CS_POSIX_V7_LP64_OFF64_LDFLAGS=_CS_POSIX_V7_LP64_OFF64_LDFLAGS => _CS_POSIX_V7_LP64_OFF64_LDFLAGS
_CS_POSIX_V7_LP64_OFF64_LIBS=_CS_POSIX_V7_LP64_OFF64_LIBS => _CS_POSIX_V7_LP64_OFF64_LIBS
_CS_POSIX_V7_LP64_OFF64_LINTFLAGS=_CS_POSIX_V7_LP64_OFF64_LINTFLAGS => _CS_POSIX_V7_LP64_OFF64_LINTFLAGS
_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS=_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS => _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS
_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS=_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS => _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS
_CS_POSIX_V7_LPBIG_OFFBIG_LIBS=_CS_POSIX_V7_LPBIG_OFFBIG_LIBS => _CS_POSIX_V7_LPBIG_OFFBIG_LIBS
_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS=_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS => _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS
_CS_V6_ENV=_CS_V6_ENV => _CS_V6_ENV
_CS_V7_ENV=_CS_V7_ENV => _CS_V7_ENV
_GETOPT_POSIX_H=_GETOPT_POSIX_H => 1
_GETOPT_CORE_H=_GETOPT_CORE_H => 1
F_ULOCK=F_ULOCK => 0
F_LOCK=F_LOCK => 1
F_TLOCK=F_TLOCK => 2
F_TEST=F_TEST => 3
_INTTYPES_H=_INTTYPES_H => 1
_STDINT_H=_STDINT_H => 1
__GLIBC_USE_LIB_EXT2=__GLIBC_USE_LIB_EXT2 => 0
__GLIBC_USE_IEC_60559_BFP_EXT=__GLIBC_USE_IEC_60559_BFP_EXT => 0
__GLIBC_USE_IEC_60559_FUNCS_EXT=__GLIBC_USE_IEC_60559_FUNCS_EXT => 0
__GLIBC_USE_IEC_60559_TYPES_EXT=__GLIBC_USE_IEC_60559_TYPES_EXT => 0
_BITS_WCHAR_H=_BITS_WCHAR_H => 1
__WCHAR_MAX=__WCHAR_MAX => (0x7fffffff + L'\0')
__WCHAR_MIN=__WCHAR_MIN => (-__WCHAR_MAX - 1)
_BITS_STDINT_INTN_H=_BITS_STDINT_INTN_H => 1
_BITS_STDINT_UINTN_H=_BITS_STDINT_UINTN_H => 1
__INT64_C=__INT64_C(c) => c ## L
__UINT64_C=__UINT64_C(c) => c ## UL
INT8_MIN=INT8_MIN => (-128)
INT16_MIN=INT16_MIN => (-32767-1)
INT32_MIN=INT32_MIN => (-2147483647-1)
INT64_MIN=INT64_MIN => (-__INT64_C(9223372036854775807)-1)
INT8_MAX=INT8_MAX => (127)
INT16_MAX=INT16_MAX => (32767)
INT32_MAX=INT32_MAX => (2147483647)
INT64_MAX=INT64_MAX => (__INT64_C(9223372036854775807))
UINT8_MAX=UINT8_MAX => (255)
UINT16_MAX=UINT16_MAX => (65535)
UINT32_MAX=UINT32_MAX => (4294967295U)
UINT64_MAX=UINT64_MAX => (__UINT64_C(18446744073709551615))
INT_LEAST8_MIN=INT_LEAST8_MIN => (-128)
INT_LEAST16_MIN=INT_LEAST16_MIN => (-32767-1)
INT_LEAST32_MIN=INT_LEAST32_MIN => (-2147483647-1)
INT_LEAST64_MIN=INT_LEAST64_MIN => (-__INT64_C(9223372036854775807)-1)
INT_LEAST8_MAX=INT_LEAST8_MAX => (127)
INT_LEAST16_MAX=INT_LEAST16_MAX => (32767)
INT_LEAST32_MAX=INT_LEAST32_MAX => (2147483647)
INT_LEAST64_MAX=INT_LEAST64_MAX => (__INT64_C(9223372036854775807))
UINT_LEAST8_MAX=UINT_LEAST8_MAX => (255)
UINT_LEAST16_MAX=UINT_LEAST16_MAX => (65535)
UINT_LEAST32_MAX=UINT_LEAST32_MAX => (4294967295U)
UINT_LEAST64_MAX=UINT_LEAST64_MAX => (__UINT64_C(18446744073709551615))
INT_FAST8_MIN=INT_FAST8_MIN => (-128)
INT_FAST16_MIN=INT_FAST16_MIN => (-9223372036854775807L-1)
INT_FAST32_MIN=INT_FAST32_MIN => (-9223372036854775807L-1)
INT_FAST64_MIN=INT_FAST64_MIN => (-__INT64_C(9223372036854775807)-1)
INT_FAST8_MAX=INT_FAST8_MAX => (127)
INT_FAST16_MAX=INT_FAST16_MAX => (9223372036854775807L)
INT_FAST32_MAX=INT_FAST32_MAX => (9223372036854775807L)
INT_FAST64_MAX=INT_FAST64_MAX => (__INT64_C(9223372036854775807))
UINT_FAST8_MAX=UINT_FAST8_MAX => (255)
UINT_FAST16_MAX=UINT_FAST16_MAX => (18446744073709551615UL)
UINT_FAST32_MAX=UINT_FAST32_MAX => (18446744073709551615UL)
UINT_FAST64_MAX=UINT_FAST64_MAX => (__UINT64_C(18446744073709551615))
INTPTR_MIN=INTPTR_MIN => (-9223372036854775807L-1)
INTPTR_MAX=INTPTR_MAX => (9223372036854775807L)
UINTPTR_MAX=UINTPTR_MAX => (18446744073709551615UL)
INTMAX_MIN=INTMAX_MIN => (-__INT64_C(9223372036854775807)-1)
INTMAX_MAX=INTMAX_MAX => (__INT64_C(9223372036854775807))
UINTMAX_MAX=UINTMAX_MAX => (__UINT64_C(18446744073709551615))
PTRDIFF_MIN=PTRDIFF_MIN => (-9223372036854775807L-1)
PTRDIFF_MAX=PTRDIFF_MAX => (9223372036854775807L)
SIG_ATOMIC_MIN=SIG_ATOMIC_MIN => (-2147483647-1)
SIG_ATOMIC_MAX=SIG_ATOMIC_MAX => (2147483647)
SIZE_MAX=SIZE_MAX => (18446744073709551615UL)
WCHAR_MIN=WCHAR_MIN => __WCHAR_MIN
WCHAR_MAX=WCHAR_MAX => __WCHAR_MAX
WINT_MIN=WINT_MIN => (0u)
WINT_MAX=WINT_MAX => (4294967295u)
INT8_C=INT8_C(c) => c
INT16_C=INT16_C(c) => c
INT32_C=INT32_C(c) => c
INT64_C=INT64_C(c) => c ## L
UINT8_C=UINT8_C(c) => c
UINT16_C=UINT16_C(c) => c
UINT32_C=UINT32_C(c) => c ## U
UINT64_C=UINT64_C(c) => c ## UL
INTMAX_C=INTMAX_C(c) => c ## L
UINTMAX_C=UINTMAX_C(c) => c ## UL
__gwchar_t=__gwchar_t => wchar_t
____gwchar_t_defined=____gwchar_t_defined => 1
__PRI64_PREFIX=__PRI64_PREFIX => "l"
__PRIPTR_PREFIX=__PRIPTR_PREFIX => "l"
PRId8=PRId8 => "d"
PRId16=PRId16 => "d"
PRId32=PRId32 => "d"
PRId64=PRId64 => __PRI64_PREFIX "d"
PRIdLEAST8=PRIdLEAST8 => "d"
PRIdLEAST16=PRIdLEAST16 => "d"
PRIdLEAST32=PRIdLEAST32 => "d"
PRIdLEAST64=PRIdLEAST64 => __PRI64_PREFIX "d"
PRIdFAST8=PRIdFAST8 => "d"
PRIdFAST16=PRIdFAST16 => __PRIPTR_PREFIX "d"
PRIdFAST32=PRIdFAST32 => __PRIPTR_PREFIX "d"
PRIdFAST64=PRIdFAST64 => __PRI64_PREFIX "d"
PRIi8=PRIi8 => "i"
PRIi16=PRIi16 => "i"
PRIi32=PRIi32 => "i"
PRIi64=PRIi64 => __PRI64_PREFIX "i"
PRIiLEAST8=PRIiLEAST8 => "i"
PRIiLEAST16=PRIiLEAST16 => "i"
PRIiLEAST32=PRIiLEAST32 => "i"
PRIiLEAST64=PRIiLEAST64 => __PRI64_PREFIX "i"
PRIiFAST8=PRIiFAST8 => "i"
PRIiFAST16=PRIiFAST16 => __PRIPTR_PREFIX "i"
PRIiFAST32=PRIiFAST32 => __PRIPTR_PREFIX "i"
PRIiFAST64=PRIiFAST64 => __PRI64_PREFIX "i"
PRIo8=PRIo8 => "o"
PRIo16=PRIo16 => "o"
PRIo32=PRIo32 => "o"
PRIo64=PRIo64 => __PRI64_PREFIX "o"
PRIoLEAST8=PRIoLEAST8 => "o"
PRIoLEAST16=PRIoLEAST16 => "o"
PRIoLEAST32=PRIoLEAST32 => "o"
PRIoLEAST64=PRIoLEAST64 => __PRI64_PREFIX "o"
PRIoFAST8=PRIoFAST8 => "o"
PRIoFAST16=PRIoFAST16 => __PRIPTR_PREFIX "o"
PRIoFAST32=PRIoFAST32 => __PRIPTR_PREFIX "o"
PRIoFAST64=PRIoFAST64 => __PRI64_PREFIX "o"
PRIu8=PRIu8 => "u"
PRIu16=PRIu16 => "u"
PRIu32=PRIu32 => "u"
PRIu64=PRIu64 => __PRI64_PREFIX "u"
PRIuLEAST8=PRIuLEAST8 => "u"
PRIuLEAST16=PRIuLEAST16 => "u"
PRIuLEAST32=PRIuLEAST32 => "u"
PRIuLEAST64=PRIuLEAST64 => __PRI64_PREFIX "u"
PRIuFAST8=PRIuFAST8 => "u"
PRIuFAST16=PRIuFAST16 => __PRIPTR_PREFIX "u"
PRIuFAST32=PRIuFAST32 => __PRIPTR_PREFIX "u"
PRIuFAST64=PRIuFAST64 => __PRI64_PREFIX "u"
PRIx8=PRIx8 => "x"
PRIx16=PRIx16 => "x"
PRIx32=PRIx32 => "x"
PRIx64=PRIx64 => __PRI64_PREFIX "x"
PRIxLEAST8=PRIxLEAST8 => "x"
PRIxLEAST16=PRIxLEAST16 => "x"
PRIxLEAST32=PRIxLEAST32 => "x"
PRIxLEAST64=PRIxLEAST64 => __PRI64_PREFIX "x"
PRIxFAST8=PRIxFAST8 => "x"
PRIxFAST16=PRIxFAST16 => __PRIPTR_PREFIX "x"
PRIxFAST32=PRIxFAST32 => __PRIPTR_PREFIX "x"
PRIxFAST64=PRIxFAST64 => __PRI64_PREFIX "x"
PRIX8=PRIX8 => "X"
PRIX16=PRIX16 => "X"
PRIX32=PRIX32 => "X"
PRIX64=PRIX64 => __PRI64_PREFIX "X"
PRIXLEAST8=PRIXLEAST8 => "X"
PRIXLEAST16=PRIXLEAST16 => "X"
PRIXLEAST32=PRIXLEAST32 => "X"
PRIXLEAST64=PRIXLEAST64 => __PRI64_PREFIX "X"
PRIXFAST8=PRIXFAST8 => "X"
PRIXFAST16=PRIXFAST16 => __PRIPTR_PREFIX "X"
PRIXFAST32=PRIXFAST32 => __PRIPTR_PREFIX "X"
PRIXFAST64=PRIXFAST64 => __PRI64_PREFIX "X"
PRIdMAX=PRIdMAX => __PRI64_PREFIX "d"
PRIiMAX=PRIiMAX => __PRI64_PREFIX "i"
PRIoMAX=PRIoMAX => __PRI64_PREFIX "o"
PRIuMAX=PRIuMAX => __PRI64_PREFIX "u"
PRIxMAX=PRIxMAX => __PRI64_PREFIX "x"
PRIXMAX=PRIXMAX => __PRI64_PREFIX "X"
PRIdPTR=PRIdPTR => __PRIPTR_PREFIX "d"
PRIiPTR=PRIiPTR => __PRIPTR_PREFIX "i"
PRIoPTR=PRIoPTR => __PRIPTR_PREFIX "o"
PRIuPTR=PRIuPTR => __PRIPTR_PREFIX "u"
PRIxPTR=PRIxPTR => __PRIPTR_PREFIX "x"
PRIXPTR=PRIXPTR => __PRIPTR_PREFIX "X"
SCNd8=SCNd8 => "hhd"
SCNd16=SCNd16 => "hd"
SCNd32=SCNd32 => "d"
SCNd64=SCNd64 => __PRI64_PREFIX "d"
SCNdLEAST8=SCNdLEAST8 => "hhd"
SCNdLEAST16=SCNdLEAST16 => "hd"
SCNdLEAST32=SCNdLEAST32 => "d"
SCNdLEAST64=SCNdLEAST64 => __PRI64_PREFIX "d"
SCNdFAST8=SCNdFAST8 => "hhd"
SCNdFAST16=SCNdFAST16 => __PRIPTR_PREFIX "d"
SCNdFAST32=SCNdFAST32 => __PRIPTR_PREFIX "d"
SCNdFAST64=SCNdFAST64 => __PRI64_PREFIX "d"
SCNi8=SCNi8 => "hhi"
SCNi16=SCNi16 => "hi"
SCNi32=SCNi32 => "i"
SCNi64=SCNi64 => __PRI64_PREFIX "i"
SCNiLEAST8=SCNiLEAST8 => "hhi"
SCNiLEAST16=SCNiLEAST16 => "hi"
SCNiLEAST32=SCNiLEAST32 => "i"
SCNiLEAST64=SCNiLEAST64 => __PRI64_PREFIX "i"
SCNiFAST8=SCNiFAST8 => "hhi"
SCNiFAST16=SCNiFAST16 => __PRIPTR_PREFIX "i"
SCNiFAST32=SCNiFAST32 => __PRIPTR_PREFIX "i"
SCNiFAST64=SCNiFAST64 => __PRI64_PREFIX "i"
SCNu8=SCNu8 => "hhu"
SCNu16=SCNu16 => "hu"
SCNu32=SCNu32 => "u"
SCNu64=SCNu64 => __PRI64_PREFIX "u"
SCNuLEAST8=SCNuLEAST8 => "hhu"
SCNuLEAST16=SCNuLEAST16 => "hu"
SCNuLEAST32=SCNuLEAST32 => "u"
SCNuLEAST64=SCNuLEAST64 => __PRI64_PREFIX "u"
SCNuFAST8=SCNuFAST8 => "hhu"
SCNuFAST16=SCNuFAST16 => __PRIPTR_PREFIX "u"
SCNuFAST32=SCNuFAST32 => __PRIPTR_PREFIX "u"
SCNuFAST64=SCNuFAST64 => __PRI64_PREFIX "u"
SCNo8=SCNo8 => "hho"
SCNo16=SCNo16 => "ho"
SCNo32=SCNo32 => "o"
SCNo64=SCNo64 => __PRI64_PREFIX "o"
SCNoLEAST8=SCNoLEAST8 => "hho"
SCNoLEAST16=SCNoLEAST16 => "ho"
SCNoLEAST32=SCNoLEAST32 => "o"
SCNoLEAST64=SCNoLEAST64 => __PRI64_PREFIX "o"
SCNoFAST8=SCNoFAST8 => "hho"
SCNoFAST16=SCNoFAST16 => __PRIPTR_PREFIX "o"
SCNoFAST32=SCNoFAST32 => __PRIPTR_PREFIX "o"
SCNoFAST64=SCNoFAST64 => __PRI64_PREFIX "o"
SCNx8=SCNx8 => "hhx"
SCNx16=SCNx16 => "hx"
SCNx32=SCNx32 => "x"
SCNx64=SCNx64 => __PRI64_PREFIX "x"
SCNxLEAST8=SCNxLEAST8 => "hhx"
SCNxLEAST16=SCNxLEAST16 => "hx"
SCNxLEAST32=SCNxLEAST32 => "x"
SCNxLEAST64=SCNxLEAST64 => __PRI64_PREFIX "x"
SCNxFAST8=SCNxFAST8 => "hhx"
SCNxFAST16=SCNxFAST16 => __PRIPTR_PREFIX "x"
SCNxFAST32=SCNxFAST32 => __PRIPTR_PREFIX "x"
SCNxFAST64=SCNxFAST64 => __PRI64_PREFIX "x"
SCNdMAX=SCNdMAX => __PRI64_PREFIX "d"
SCNiMAX=SCNiMAX => __PRI64_PREFIX "i"
SCNoMAX=SCNoMAX => __PRI64_PREFIX "o"
SCNuMAX=SCNuMAX => __PRI64_PREFIX "u"
SCNxMAX=SCNxMAX => __PRI64_PREFIX "x"
SCNdPTR=SCNdPTR => __PRIPTR_PREFIX "d"
SCNiPTR=SCNiPTR => __PRIPTR_PREFIX "i"
SCNoPTR=SCNoPTR => __PRIPTR_PREFIX "o"
SCNuPTR=SCNuPTR => __PRIPTR_PREFIX "u"
SCNxPTR=SCNxPTR => __PRIPTR_PREFIX "x"
_SYS_TYPES_H=_SYS_TYPES_H => 1
__u_char_defined=__u_char_defined
__ino_t_defined=__ino_t_defined
__dev_t_defined=__dev_t_defined
__mode_t_defined=__mode_t_defined
__nlink_t_defined=__nlink_t_defined
__id_t_defined=__id_t_defined
__daddr_t_defined=__daddr_t_defined
__key_t_defined=__key_t_defined
__clock_t_defined=__clock_t_defined => 1
__clockid_t_defined=__clockid_t_defined => 1
__time_t_defined=__time_t_defined => 1
__timer_t_defined=__timer_t_defined => 1
__BIT_TYPES_DEFINED__=__BIT_TYPES_DEFINED__ => 1
_ENDIAN_H=_ENDIAN_H => 1
__LITTLE_ENDIAN=__LITTLE_ENDIAN => 1234
__BIG_ENDIAN=__BIG_ENDIAN => 4321
__PDP_ENDIAN=__PDP_ENDIAN => 3412
__BYTE_ORDER=__BYTE_ORDER => __LITTLE_ENDIAN
__FLOAT_WORD_ORDER=__FLOAT_WORD_ORDER => __BYTE_ORDER
LITTLE_ENDIAN=LITTLE_ENDIAN => __LITTLE_ENDIAN
BIG_ENDIAN=BIG_ENDIAN => __BIG_ENDIAN
PDP_ENDIAN=PDP_ENDIAN => __PDP_ENDIAN
BYTE_ORDER=BYTE_ORDER => __BYTE_ORDER
__LONG_LONG_PAIR=__LONG_LONG_PAIR(HI, LO) => LO, HI
_BITS_BYTESWAP_H=_BITS_BYTESWAP_H => 1
__bswap_constant_16=__bswap_constant_16(x) => ((unsigned short int) ((((x) >> 8) & 0xff) | (((x) & 0xff) << 8)))
__bswap_16=__bswap_16(x) => (__extension__ ({ unsigned short int __x = (unsigned short int) (x); __bswap_constant_16 (__x); }))
__bswap_constant_32=__bswap_constant_32(x) => ((((x) & 0xff000000) >> 24) | (((x) & 0x00ff0000) >> 8) | (((x) & 0x0000ff00) << 8) | (((x) & 0x000000ff) << 24))
__bswap_32=__bswap_32(x) => (__extension__ ({ unsigned int __x = (x); __bswap_constant_32 (__x); }))
__bswap_constant_64=__bswap_constant_64(x) => ((((x) & 0xff00000000000000ull) >> 56) | (((x) & 0x00ff000000000000ull) >> 40) | (((x) & 0x0000ff0000000000ull) >> 24) | (((x) & 0x000000ff00000000ull) >> 8) | (((x) & 0x00000000ff000000ull) << 8) | (((x) & 0x0000000000ff0000ull) << 24) | (((x) & 0x000000000000ff00ull) << 40) | (((x) & 0x00000000000000ffull) << 56))
_BITS_UINTN_IDENTITY_H=_BITS_UINTN_IDENTITY_H => 1
htobe16=htobe16(x) => __bswap_16 (x)
htole16=htole16(x) => __uint16_identity (x)
be16toh=be16toh(x) => __bswap_16 (x)
le16toh=le16toh(x) => __uint16_identity (x)
htobe32=htobe32(x) => __bswap_32 (x)
htole32=htole32(x) => __uint32_identity (x)
be32toh=be32toh(x) => __bswap_32 (x)
le32toh=le32toh(x) => __uint32_identity (x)
htobe64=htobe64(x) => __bswap_64 (x)
htole64=htole64(x) => __uint64_identity (x)
be64toh=be64toh(x) => __bswap_64 (x)
le64toh=le64toh(x) => __uint64_identity (x)
_SYS_SELECT_H=_SYS_SELECT_H => 1
__FD_ZERO=__FD_ZERO(set) => do { unsigned int __i; fd_set *__arr = (set); for (__i = 0; __i < sizeof (fd_set) / sizeof (__fd_mask); ++__i) __FDS_BITS (__arr)[__i] = 0; } while (0)
__FD_SET=__FD_SET(d, set) => ((void) (__FDS_BITS (set)[__FD_ELT (d)] |= __FD_MASK (d)))
__FD_CLR=__FD_CLR(d, set) => ((void) (__FDS_BITS (set)[__FD_ELT (d)] &= ~__FD_MASK (d)))
__FD_ISSET=__FD_ISSET(d, set) => ((__FDS_BITS (set)[__FD_ELT (d)] & __FD_MASK (d)) != 0)
__sigset_t_defined=__sigset_t_defined => 1
____sigset_t_defined=____sigset_t_defined
_SIGSET_NWORDS=_SIGSET_NWORDS => (1024 / (8 * sizeof (unsigned long int)))
__timeval_defined=__timeval_defined => 1
__timespec_defined=__timespec_defined => 1
__suseconds_t_defined=__suseconds_t_defined
__NFDBITS=__NFDBITS => (8 * (int) sizeof (__fd_mask))
__FD_ELT=__FD_ELT(d) => ((d) / __NFDBITS)
__FD_MASK=__FD_MASK(d) => ((__fd_mask) (1UL << ((d) % __NFDBITS)))
__FDS_BITS=__FDS_BITS(set) => ((set)->__fds_bits)
FD_SETSIZE=FD_SETSIZE => __FD_SETSIZE
NFDBITS=NFDBITS => __NFDBITS
FD_SET=FD_SET(fd, fdsetp) => __FD_SET (fd, fdsetp)
FD_CLR=FD_CLR(fd, fdsetp) => __FD_CLR (fd, fdsetp)
FD_ISSET=FD_ISSET(fd, fdsetp) => __FD_ISSET (fd, fdsetp)
FD_ZERO=FD_ZERO(fdsetp) => __FD_ZERO (fdsetp)
_SYS_SYSMACROS_H=_SYS_SYSMACROS_H => 1
_BITS_SYSMACROS_H=_BITS_SYSMACROS_H => 1
__SYSMACROS_DM=__SYSMACROS_DM(symbol) => __SYSMACROS_DM1 (In the GNU C Library, #symbol is defined\n by <sys/sysmacros.h>. For historical compatibility, it is\n currently defined by <sys/types.h> as well, but we plan to\n remove this soon. To use #symbol, include <sys/sysmacros.h>\n directly. If you did not intend to use a system-defined macro\n #symbol, you should undefine it after including <sys/types.h>.)
__SYSMACROS_DM1=__SYSMACROS_DM1(__VA_ARGS__...) => __glibc_macro_warning (#__VA_ARGS__)
major=major(dev) => __SYSMACROS_DM (major) gnu_dev_major (dev)
minor=minor(dev) => __SYSMACROS_DM (minor) gnu_dev_minor (dev)
makedev=makedev(maj, min) => __SYSMACROS_DM (makedev) gnu_dev_makedev (maj, min)
__blksize_t_defined=__blksize_t_defined
__blkcnt_t_defined=__blkcnt_t_defined
__fsblkcnt_t_defined=__fsblkcnt_t_defined
__fsfilcnt_t_defined=__fsfilcnt_t_defined
_BITS_PTHREADTYPES_COMMON_H=_BITS_PTHREADTYPES_COMMON_H => 1
_THREAD_SHARED_TYPES_H=_THREAD_SHARED_TYPES_H => 1
_BITS_PTHREADTYPES_ARCH_H=_BITS_PTHREADTYPES_ARCH_H => 1
__SIZEOF_PTHREAD_MUTEX_T=__SIZEOF_PTHREAD_MUTEX_T => 40
__SIZEOF_PTHREAD_ATTR_T=__SIZEOF_PTHREAD_ATTR_T => 56
__SIZEOF_PTHREAD_RWLOCK_T=__SIZEOF_PTHREAD_RWLOCK_T => 56
__SIZEOF_PTHREAD_BARRIER_T=__SIZEOF_PTHREAD_BARRIER_T => 32
__SIZEOF_PTHREAD_MUTEXATTR_T=__SIZEOF_PTHREAD_MUTEXATTR_T => 4
__SIZEOF_PTHREAD_COND_T=__SIZEOF_PTHREAD_COND_T => 48
__SIZEOF_PTHREAD_CONDATTR_T=__SIZEOF_PTHREAD_CONDATTR_T => 4
__SIZEOF_PTHREAD_RWLOCKATTR_T=__SIZEOF_PTHREAD_RWLOCKATTR_T => 8
__SIZEOF_PTHREAD_BARRIERATTR_T=__SIZEOF_PTHREAD_BARRIERATTR_T => 4
__PTHREAD_COMPAT_PADDING_MID=__PTHREAD_COMPAT_PADDING_MID
__PTHREAD_COMPAT_PADDING_END=__PTHREAD_COMPAT_PADDING_END
__PTHREAD_MUTEX_LOCK_ELISION=__PTHREAD_MUTEX_LOCK_ELISION => 1
__PTHREAD_MUTEX_NUSERS_AFTER_KIND=__PTHREAD_MUTEX_NUSERS_AFTER_KIND => 0
__PTHREAD_MUTEX_USE_UNION=__PTHREAD_MUTEX_USE_UNION => 0
__LOCK_ALIGNMENT=__LOCK_ALIGNMENT
__ONCE_ALIGNMENT=__ONCE_ALIGNMENT
__PTHREAD_RWLOCK_ELISION_EXTRA=__PTHREAD_RWLOCK_ELISION_EXTRA => 0, { 0, 0, 0, 0, 0, 0, 0 }
__PTHREAD_RWLOCK_INT_FLAGS_SHARED=__PTHREAD_RWLOCK_INT_FLAGS_SHARED => 1
__PTHREAD_SPINS_DATA=__PTHREAD_SPINS_DATA => short __spins; short __elision
__PTHREAD_SPINS=__PTHREAD_SPINS => 0, 0
__PTHREAD_MUTEX_HAVE_PREV=__PTHREAD_MUTEX_HAVE_PREV => 1
__have_pthread_attr_t=__have_pthread_attr_t => 1
SSH_STRINGIFY=SSH_STRINGIFY(s) => SSH_TOSTRING(s)
SSH_TOSTRING=SSH_TOSTRING(s) => #s
SSH_VERSION_INT=SSH_VERSION_INT(a, b, c) => ((a) << 16 | (b) << 8 | (c))
SSH_VERSION_DOT=SSH_VERSION_DOT(a, b, c) => a ## . ## b ## . ## c
SSH_VERSION=SSH_VERSION(a, b, c) => SSH_VERSION_DOT(a, b, c)
LIBSSH_VERSION_MAJOR=LIBSSH_VERSION_MAJOR => 0
LIBSSH_VERSION_MINOR=LIBSSH_VERSION_MINOR => 7
LIBSSH_VERSION_MICRO=LIBSSH_VERSION_MICRO => 0
LIBSSH_VERSION_INT=LIBSSH_VERSION_INT => SSH_VERSION_INT(LIBSSH_VERSION_MAJOR, LIBSSH_VERSION_MINOR, LIBSSH_VERSION_MICRO)
LIBSSH_VERSION=LIBSSH_VERSION => SSH_VERSION(LIBSSH_VERSION_MAJOR, LIBSSH_VERSION_MINOR, LIBSSH_VERSION_MICRO)
PRINTF_ATTRIBUTE=PRINTF_ATTRIBUTE(a, b) => __attribute__ ((__format__ (__printf__, a, b)))
SSH_DEPRECATED=SSH_DEPRECATED => __attribute__ ((deprecated))
SSH_INVALID_SOCKET=SSH_INVALID_SOCKET => ((socket_t) -1)
SSH_CRYPT=SSH_CRYPT => 2
SSH_MAC=SSH_MAC => 3
SSH_COMP=SSH_COMP => 4
SSH_LANG=SSH_LANG => 5
SSH_AUTH_METHOD_UNKNOWN=SSH_AUTH_METHOD_UNKNOWN => 0
SSH_AUTH_METHOD_NONE=SSH_AUTH_METHOD_NONE => 0x0001
SSH_AUTH_METHOD_PASSWORD=SSH_AUTH_METHOD_PASSWORD => 0x0002
SSH_AUTH_METHOD_PUBLICKEY=SSH_AUTH_METHOD_PUBLICKEY => 0x0004
SSH_AUTH_METHOD_HOSTBASED=SSH_AUTH_METHOD_HOSTBASED => 0x0008
SSH_AUTH_METHOD_INTERACTIVE=SSH_AUTH_METHOD_INTERACTIVE => 0x0010
SSH_AUTH_METHOD_GSSAPI_MIC=SSH_AUTH_METHOD_GSSAPI_MIC => 0x0020
SSH_CLOSED=SSH_CLOSED => 0x01
SSH_READ_PENDING=SSH_READ_PENDING => 0x02
SSH_CLOSED_ERROR=SSH_CLOSED_ERROR => 0x04
SSH_WRITE_PENDING=SSH_WRITE_PENDING => 0x08
MD5_DIGEST_LEN=MD5_DIGEST_LEN => 16
SSH_OK=SSH_OK => 0
SSH_ERROR=SSH_ERROR => -1
SSH_AGAIN=SSH_AGAIN => -2
SSH_EOF=SSH_EOF => -127
SSH_LOG_RARE=SSH_LOG_RARE => SSH_LOG_WARNING
SSH_LOG_NONE=SSH_LOG_NONE => 0
SSH_LOG_WARN=SSH_LOG_WARN => 1
SSH_LOG_INFO=SSH_LOG_INFO => 2
SSH_LOG_DEBUG=SSH_LOG_DEBUG => 3
SSH_LOG_TRACE=SSH_LOG_TRACE => 4
LEGACY_H_=LEGACY_H_
SFTP_H=SFTP_H
LIBSFTP_VERSION=LIBSFTP_VERSION => 3
SFTP_HANDLES=SFTP_HANDLES => 256
SSH_FXP_INIT=SSH_FXP_INIT => 1
SSH_FXP_VERSION=SSH_FXP_VERSION => 2
SSH_FXP_OPEN=SSH_FXP_OPEN => 3
SSH_FXP_CLOSE=SSH_FXP_CLOSE => 4
SSH_FXP_READ=SSH_FXP_READ => 5
SSH_FXP_WRITE=SSH_FXP_WRITE => 6
SSH_FXP_LSTAT=SSH_FXP_LSTAT => 7
SSH_FXP_FSTAT=SSH_FXP_FSTAT => 8
SSH_FXP_SETSTAT=SSH_FXP_SETSTAT => 9
SSH_FXP_FSETSTAT=SSH_FXP_FSETSTAT => 10
SSH_FXP_OPENDIR=SSH_FXP_OPENDIR => 11
SSH_FXP_READDIR=SSH_FXP_READDIR => 12
SSH_FXP_REMOVE=SSH_FXP_REMOVE => 13
SSH_FXP_MKDIR=SSH_FXP_MKDIR => 14
SSH_FXP_RMDIR=SSH_FXP_RMDIR => 15
SSH_FXP_REALPATH=SSH_FXP_REALPATH => 16
SSH_FXP_STAT=SSH_FXP_STAT => 17
SSH_FXP_RENAME=SSH_FXP_RENAME => 18
SSH_FXP_READLINK=SSH_FXP_READLINK => 19
SSH_FXP_SYMLINK=SSH_FXP_SYMLINK => 20
SSH_FXP_STATUS=SSH_FXP_STATUS => 101
SSH_FXP_HANDLE=SSH_FXP_HANDLE => 102
SSH_FXP_DATA=SSH_FXP_DATA => 103
SSH_FXP_NAME=SSH_FXP_NAME => 104
SSH_FXP_ATTRS=SSH_FXP_ATTRS => 105
SSH_FXP_EXTENDED=SSH_FXP_EXTENDED => 200
SSH_FXP_EXTENDED_REPLY=SSH_FXP_EXTENDED_REPLY => 201
SSH_FILEXFER_ATTR_SIZE=SSH_FILEXFER_ATTR_SIZE => 0x00000001
SSH_FILEXFER_ATTR_PERMISSIONS=SSH_FILEXFER_ATTR_PERMISSIONS => 0x00000004
SSH_FILEXFER_ATTR_ACCESSTIME=SSH_FILEXFER_ATTR_ACCESSTIME => 0x00000008
SSH_FILEXFER_ATTR_ACMODTIME=SSH_FILEXFER_ATTR_ACMODTIME => 0x00000008
SSH_FILEXFER_ATTR_CREATETIME=SSH_FILEXFER_ATTR_CREATETIME => 0x00000010
SSH_FILEXFER_ATTR_MODIFYTIME=SSH_FILEXFER_ATTR_MODIFYTIME => 0x00000020
SSH_FILEXFER_ATTR_ACL=SSH_FILEXFER_ATTR_ACL => 0x00000040
SSH_FILEXFER_ATTR_OWNERGROUP=SSH_FILEXFER_ATTR_OWNERGROUP => 0x00000080
SSH_FILEXFER_ATTR_SUBSECOND_TIMES=SSH_FILEXFER_ATTR_SUBSECOND_TIMES => 0x00000100
SSH_FILEXFER_ATTR_EXTENDED=SSH_FILEXFER_ATTR_EXTENDED => 0x80000000
SSH_FILEXFER_ATTR_UIDGID=SSH_FILEXFER_ATTR_UIDGID => 0x00000002
SSH_FILEXFER_TYPE_REGULAR=SSH_FILEXFER_TYPE_REGULAR => 1
SSH_FILEXFER_TYPE_DIRECTORY=SSH_FILEXFER_TYPE_DIRECTORY => 2
SSH_FILEXFER_TYPE_SYMLINK=SSH_FILEXFER_TYPE_SYMLINK => 3
SSH_FILEXFER_TYPE_SPECIAL=SSH_FILEXFER_TYPE_SPECIAL => 4
SSH_FILEXFER_TYPE_UNKNOWN=SSH_FILEXFER_TYPE_UNKNOWN => 5
SSH_FX_OK=SSH_FX_OK => 0
SSH_FX_EOF=SSH_FX_EOF => 1
SSH_FX_NO_SUCH_FILE=SSH_FX_NO_SUCH_FILE => 2
SSH_FX_PERMISSION_DENIED=SSH_FX_PERMISSION_DENIED => 3
SSH_FX_FAILURE=SSH_FX_FAILURE => 4
SSH_FX_BAD_MESSAGE=SSH_FX_BAD_MESSAGE => 5
SSH_FX_NO_CONNECTION=SSH_FX_NO_CONNECTION => 6
SSH_FX_CONNECTION_LOST=SSH_FX_CONNECTION_LOST => 7
SSH_FX_OP_UNSUPPORTED=SSH_FX_OP_UNSUPPORTED => 8
SSH_FX_INVALID_HANDLE=SSH_FX_INVALID_HANDLE => 9
SSH_FX_NO_SUCH_PATH=SSH_FX_NO_SUCH_PATH => 10
SSH_FX_FILE_ALREADY_EXISTS=SSH_FX_FILE_ALREADY_EXISTS => 11
SSH_FX_WRITE_PROTECT=SSH_FX_WRITE_PROTECT => 12
SSH_FX_NO_MEDIA=SSH_FX_NO_MEDIA => 13
SSH_FXF_READ=SSH_FXF_READ => 0x01
SSH_FXF_WRITE=SSH_FXF_WRITE => 0x02
SSH_FXF_APPEND=SSH_FXF_APPEND => 0x04
SSH_FXF_CREAT=SSH_FXF_CREAT => 0x08
SSH_FXF_TRUNC=SSH_FXF_TRUNC => 0x10
SSH_FXF_EXCL=SSH_FXF_EXCL => 0x20
SSH_FXF_TEXT=SSH_FXF_TEXT => 0x40
SSH_S_IFMT=SSH_S_IFMT => 00170000
SSH_S_IFSOCK=SSH_S_IFSOCK => 0140000
SSH_S_IFLNK=SSH_S_IFLNK => 0120000
SSH_S_IFREG=SSH_S_IFREG => 0100000
SSH_S_IFBLK=SSH_S_IFBLK => 0060000
SSH_S_IFDIR=SSH_S_IFDIR => 0040000
SSH_S_IFCHR=SSH_S_IFCHR => 0020000
SSH_S_IFIFO=SSH_S_IFIFO => 0010000
SSH_FXF_RENAME_OVERWRITE=SSH_FXF_RENAME_OVERWRITE => 0x00000001
SSH_FXF_RENAME_ATOMIC=SSH_FXF_RENAME_ATOMIC => 0x00000002
SSH_FXF_RENAME_NATIVE=SSH_FXF_RENAME_NATIVE => 0x00000004
SFTP_OPEN=SFTP_OPEN => SSH_FXP_OPEN
SFTP_CLOSE=SFTP_CLOSE => SSH_FXP_CLOSE
SFTP_READ=SFTP_READ => SSH_FXP_READ
SFTP_WRITE=SFTP_WRITE => SSH_FXP_WRITE
SFTP_LSTAT=SFTP_LSTAT => SSH_FXP_LSTAT
SFTP_FSTAT=SFTP_FSTAT => SSH_FXP_FSTAT
SFTP_SETSTAT=SFTP_SETSTAT => SSH_FXP_SETSTAT
SFTP_FSETSTAT=SFTP_FSETSTAT => SSH_FXP_FSETSTAT
SFTP_OPENDIR=SFTP_OPENDIR => SSH_FXP_OPENDIR
SFTP_READDIR=SFTP_READDIR => SSH_FXP_READDIR
SFTP_REMOVE=SFTP_REMOVE => SSH_FXP_REMOVE
SFTP_MKDIR=SFTP_MKDIR => SSH_FXP_MKDIR
SFTP_RMDIR=SFTP_RMDIR => SSH_FXP_RMDIR
SFTP_REALPATH=SFTP_REALPATH => SSH_FXP_REALPATH
SFTP_STAT=SFTP_STAT => SSH_FXP_STAT
SFTP_RENAME=SFTP_RENAME => SSH_FXP_RENAME
SFTP_READLINK=SFTP_READLINK => SSH_FXP_READLINK
SFTP_SYMLINK=SFTP_SYMLINK => SSH_FXP_SYMLINK
SSH_FXE_STATVFS_ST_RDONLY=SSH_FXE_STATVFS_ST_RDONLY => 0x1
SSH_FXE_STATVFS_ST_NOSUID=SSH_FXE_STATVFS_ST_NOSUID => 0x2
_SSH_CALLBACK_H=_SSH_CALLBACK_H
_STRING_H=_STRING_H => 1
__GLIBC_INTERNAL_STARTING_HEADER_IMPLEMENTATION=__GLIBC_INTERNAL_STARTING_HEADER_IMPLEMENTATION
_BITS_TYPES_LOCALE_T_H=_BITS_TYPES_LOCALE_T_H => 1
_BITS_TYPES___LOCALE_T_H=_BITS_TYPES___LOCALE_T_H => 1
strerror_r=strerror_r => __xpg_strerror_r
_STRINGS_H=_STRINGS_H => 1
SSH_SOCKET_FLOW_WRITEWILLBLOCK=SSH_SOCKET_FLOW_WRITEWILLBLOCK => 1
SSH_SOCKET_FLOW_WRITEWONTBLOCK=SSH_SOCKET_FLOW_WRITEWONTBLOCK => 2
SSH_SOCKET_EXCEPTION_EOF=SSH_SOCKET_EXCEPTION_EOF => 1
SSH_SOCKET_EXCEPTION_ERROR=SSH_SOCKET_EXCEPTION_ERROR => 2
SSH_SOCKET_CONNECTED_OK=SSH_SOCKET_CONNECTED_OK => 1
SSH_SOCKET_CONNECTED_ERROR=SSH_SOCKET_CONNECTED_ERROR => 2
SSH_SOCKET_CONNECTED_TIMEOUT=SSH_SOCKET_CONNECTED_TIMEOUT => 3
ssh_callbacks_init=ssh_callbacks_init(p) => do { (p)->size=sizeof(*(p)); } while(0);
ssh_callbacks_exists=ssh_callbacks_exists(p, c) => ( (p != NULL) && ( (char *)&((p)-> c) < (char *)(p) + (p)->size ) && ((p)-> c != NULL) )
ssh_callbacks_execute_list=ssh_callbacks_execute_list(list, cbtype, c, __VA_ARGS__...) => do { struct ssh_iterator *i = ssh_list_get_iterator(list); cbtype cb; while (i != NULL){ cb = ssh_iterator_value(cbtype, i); if (ssh_callbacks_exists(cb, c)) cb-> c (__VA_ARGS__, cb->userdata); i = i->next; } } while(0)
ssh_callbacks_iterate=ssh_callbacks_iterate(_cb_list, _cb_type, _cb_name) => do { struct ssh_iterator *_cb_i = ssh_list_get_iterator(_cb_list); _cb_type _cb; for (; _cb_i != NULL; _cb_i = _cb_i->next) { _cb = ssh_iterator_value(_cb_type, _cb_i); if (ssh_callbacks_exists(_cb, _cb_name))
ssh_callbacks_iterate_exec=ssh_callbacks_iterate_exec(_cb_name, __VA_ARGS__...) => _cb->_cb_name(__VA_ARGS__, _cb->userdata)
ssh_callbacks_iterate_end=ssh_callbacks_iterate_end() => } } while(0)
SSH_PACKET_USED=SSH_PACKET_USED => 1
SSH_PACKET_NOT_USED=SSH_PACKET_NOT_USED => 2
SSH_PACKET_CALLBACK=SSH_PACKET_CALLBACK(name) => int name (ssh_session session, uint8_t type, ssh_buffer packet, void *user)
__SSH2_H=__SSH2_H
SSH2_MSG_DISCONNECT=SSH2_MSG_DISCONNECT => 1
SSH2_MSG_IGNORE=SSH2_MSG_IGNORE => 2
SSH2_MSG_UNIMPLEMENTED=SSH2_MSG_UNIMPLEMENTED => 3
SSH2_MSG_DEBUG=SSH2_MSG_DEBUG => 4
SSH2_MSG_SERVICE_REQUEST=SSH2_MSG_SERVICE_REQUEST => 5
SSH2_MSG_SERVICE_ACCEPT=SSH2_MSG_SERVICE_ACCEPT => 6
SSH2_MSG_KEXINIT=SSH2_MSG_KEXINIT => 20
SSH2_MSG_NEWKEYS=SSH2_MSG_NEWKEYS => 21
SSH2_MSG_KEXDH_INIT=SSH2_MSG_KEXDH_INIT => 30
SSH2_MSG_KEXDH_REPLY=SSH2_MSG_KEXDH_REPLY => 31
SSH2_MSG_KEX_ECDH_INIT=SSH2_MSG_KEX_ECDH_INIT => 30
SSH2_MSG_KEX_ECDH_REPLY=SSH2_MSG_KEX_ECDH_REPLY => 31
SSH2_MSG_ECMQV_INIT=SSH2_MSG_ECMQV_INIT => 30
SSH2_MSG_ECMQV_REPLY=SSH2_MSG_ECMQV_REPLY => 31
SSH2_MSG_KEX_DH_GEX_REQUEST_OLD=SSH2_MSG_KEX_DH_GEX_REQUEST_OLD => 30
SSH2_MSG_KEX_DH_GEX_GROUP=SSH2_MSG_KEX_DH_GEX_GROUP => 31
SSH2_MSG_KEX_DH_GEX_INIT=SSH2_MSG_KEX_DH_GEX_INIT => 32
SSH2_MSG_KEX_DH_GEX_REPLY=SSH2_MSG_KEX_DH_GEX_REPLY => 33
SSH2_MSG_KEX_DH_GEX_REQUEST=SSH2_MSG_KEX_DH_GEX_REQUEST => 34
SSH2_MSG_USERAUTH_REQUEST=SSH2_MSG_USERAUTH_REQUEST => 50
SSH2_MSG_USERAUTH_FAILURE=SSH2_MSG_USERAUTH_FAILURE => 51
SSH2_MSG_USERAUTH_SUCCESS=SSH2_MSG_USERAUTH_SUCCESS => 52
SSH2_MSG_USERAUTH_BANNER=SSH2_MSG_USERAUTH_BANNER => 53
SSH2_MSG_USERAUTH_PK_OK=SSH2_MSG_USERAUTH_PK_OK => 60
SSH2_MSG_USERAUTH_PASSWD_CHANGEREQ=SSH2_MSG_USERAUTH_PASSWD_CHANGEREQ => 60
SSH2_MSG_USERAUTH_INFO_REQUEST=SSH2_MSG_USERAUTH_INFO_REQUEST => 60
SSH2_MSG_USERAUTH_GSSAPI_RESPONSE=SSH2_MSG_USERAUTH_GSSAPI_RESPONSE => 60
SSH2_MSG_USERAUTH_INFO_RESPONSE=SSH2_MSG_USERAUTH_INFO_RESPONSE => 61
SSH2_MSG_USERAUTH_GSSAPI_TOKEN=SSH2_MSG_USERAUTH_GSSAPI_TOKEN => 61
SSH2_MSG_USERAUTH_GSSAPI_EXCHANGE_COMPLETE=SSH2_MSG_USERAUTH_GSSAPI_EXCHANGE_COMPLETE => 63
SSH2_MSG_USERAUTH_GSSAPI_ERROR=SSH2_MSG_USERAUTH_GSSAPI_ERROR => 64
SSH2_MSG_USERAUTH_GSSAPI_ERRTOK=SSH2_MSG_USERAUTH_GSSAPI_ERRTOK => 65
SSH2_MSG_USERAUTH_GSSAPI_MIC=SSH2_MSG_USERAUTH_GSSAPI_MIC => 66
SSH2_MSG_GLOBAL_REQUEST=SSH2_MSG_GLOBAL_REQUEST => 80
SSH2_MSG_REQUEST_SUCCESS=SSH2_MSG_REQUEST_SUCCESS => 81
SSH2_MSG_REQUEST_FAILURE=SSH2_MSG_REQUEST_FAILURE => 82
SSH2_MSG_CHANNEL_OPEN=SSH2_MSG_CHANNEL_OPEN => 90
SSH2_MSG_CHANNEL_OPEN_CONFIRMATION=SSH2_MSG_CHANNEL_OPEN_CONFIRMATION => 91
SSH2_MSG_CHANNEL_OPEN_FAILURE=SSH2_MSG_CHANNEL_OPEN_FAILURE => 92
SSH2_MSG_CHANNEL_WINDOW_ADJUST=SSH2_MSG_CHANNEL_WINDOW_ADJUST => 93
SSH2_MSG_CHANNEL_DATA=SSH2_MSG_CHANNEL_DATA => 94
SSH2_MSG_CHANNEL_EXTENDED_DATA=SSH2_MSG_CHANNEL_EXTENDED_DATA => 95
SSH2_MSG_CHANNEL_EOF=SSH2_MSG_CHANNEL_EOF => 96
SSH2_MSG_CHANNEL_CLOSE=SSH2_MSG_CHANNEL_CLOSE => 97
SSH2_MSG_CHANNEL_REQUEST=SSH2_MSG_CHANNEL_REQUEST => 98
SSH2_MSG_CHANNEL_SUCCESS=SSH2_MSG_CHANNEL_SUCCESS => 99
SSH2_MSG_CHANNEL_FAILURE=SSH2_MSG_CHANNEL_FAILURE => 100
SSH2_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT=SSH2_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT => 1
SSH2_DISCONNECT_PROTOCOL_ERROR=SSH2_DISCONNECT_PROTOCOL_ERROR => 2
SSH2_DISCONNECT_KEY_EXCHANGE_FAILED=SSH2_DISCONNECT_KEY_EXCHANGE_FAILED => 3
SSH2_DISCONNECT_HOST_AUTHENTICATION_FAILED=SSH2_DISCONNECT_HOST_AUTHENTICATION_FAILED => 4
SSH2_DISCONNECT_RESERVED=SSH2_DISCONNECT_RESERVED => 4
SSH2_DISCONNECT_MAC_ERROR=SSH2_DISCONNECT_MAC_ERROR => 5
SSH2_DISCONNECT_COMPRESSION_ERROR=SSH2_DISCONNECT_COMPRESSION_ERROR => 6
SSH2_DISCONNECT_SERVICE_NOT_AVAILABLE=SSH2_DISCONNECT_SERVICE_NOT_AVAILABLE => 7
SSH2_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED=SSH2_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED => 8
SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE=SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE => 9
SSH2_DISCONNECT_CONNECTION_LOST=SSH2_DISCONNECT_CONNECTION_LOST => 10
SSH2_DISCONNECT_BY_APPLICATION=SSH2_DISCONNECT_BY_APPLICATION => 11
SSH2_DISCONNECT_TOO_MANY_CONNECTIONS=SSH2_DISCONNECT_TOO_MANY_CONNECTIONS => 12
SSH2_DISCONNECT_AUTH_CANCELLED_BY_USER=SSH2_DISCONNECT_AUTH_CANCELLED_BY_USER => 13
SSH2_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE=SSH2_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE => 14
SSH2_DISCONNECT_ILLEGAL_USER_NAME=SSH2_DISCONNECT_ILLEGAL_USER_NAME => 15
SSH2_OPEN_ADMINISTRATIVELY_PROHIBITED=SSH2_OPEN_ADMINISTRATIVELY_PROHIBITED => 1
SSH2_OPEN_CONNECT_FAILED=SSH2_OPEN_CONNECT_FAILED => 2
SSH2_OPEN_UNKNOWN_CHANNEL_TYPE=SSH2_OPEN_UNKNOWN_CHANNEL_TYPE => 3
SSH2_OPEN_RESOURCE_SHORTAGE=SSH2_OPEN_RESOURCE_SHORTAGE => 4
SSH2_EXTENDED_DATA_STDERR=SSH2_EXTENDED_DATA_STDERR => 1
SERVER_H=SERVER_H
SERVERBANNER=SERVERBANNER => CLIENTBANNER
